/*
 * HDRUK Gateway API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};


/// struct for typed errors of method [`count_team_unique_fields_collection_v2`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CountTeamUniqueFieldsCollectionV2Error {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`count_unique_fields_collections`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CountUniqueFieldsCollectionsError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`count_unique_fields_collections_v2`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CountUniqueFieldsCollectionsV2Error {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`count_user_unique_fields_collection_v2`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CountUserUniqueFieldsCollectionV2Error {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`create_collections`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CreateCollectionsError {
    Status401(models::CreateTeamCollections401Response),
    Status500(models::CreateAliases500Response),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`create_team_collections`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CreateTeamCollectionsError {
    Status401(models::CreateTeamCollections401Response),
    Status500(models::CreateAliases500Response),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`create_team_collections_v2`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CreateTeamCollectionsV2Error {
    Status401(models::CreateTeamCollections401Response),
    Status500(models::CreateAliases500Response),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`create_user_collections`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CreateUserCollectionsError {
    Status401(models::CreateTeamCollections401Response),
    Status500(models::CreateAliases500Response),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`delete_collections_v2`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DeleteCollectionsV2Error {
    Status404(models::FetchAliases404Response),
    Status500(models::CreateAliases500Response),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`delete_team_collections`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DeleteTeamCollectionsError {
    Status404(models::FetchAliases404Response),
    Status500(models::CreateAliases500Response),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`delete_team_collections_v2`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DeleteTeamCollectionsV2Error {
    Status404(models::FetchAliases404Response),
    Status500(models::CreateAliases500Response),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`delete_user_collections_v2`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DeleteUserCollectionsV2Error {
    Status404(models::FetchAliases404Response),
    Status500(models::CreateAliases500Response),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`edit_collections_v2`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum EditCollectionsV2Error {
    Status404(models::FetchAliases404Response),
    Status500(models::CreateAliases500Response),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`edit_team_collections`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum EditTeamCollectionsError {
    Status404(models::FetchAliases404Response),
    Status500(models::CreateAliases500Response),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`edit_team_collections_v2`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum EditTeamCollectionsV2Error {
    Status404(models::FetchAliases404Response),
    Status500(models::CreateAliases500Response),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`edit_user_collections_v2`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum EditUserCollectionsV2Error {
    Status404(models::FetchAliases404Response),
    Status500(models::CreateAliases500Response),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`fetch_all_collections`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum FetchAllCollectionsError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`fetch_all_collections_v2`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum FetchAllCollectionsV2Error {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`fetch_collections`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum FetchCollectionsError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`fetch_collections_v2`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum FetchCollectionsV2Error {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`fetch_team_active_collections_v2`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum FetchTeamActiveCollectionsV2Error {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`fetch_team_archived_collections_v2`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum FetchTeamArchivedCollectionsV2Error {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`fetch_team_collection_v2`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum FetchTeamCollectionV2Error {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`fetch_team_draft_collections_v2`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum FetchTeamDraftCollectionsV2Error {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`fetch_user_archived_collections_v2`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum FetchUserArchivedCollectionsV2Error {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`fetch_user_collection_v2`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum FetchUserCollectionV2Error {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`fetch_user_collections_v2`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum FetchUserCollectionsV2Error {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`fetch_user_draft_collections_v2`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum FetchUserDraftCollectionsV2Error {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`update_collections_v2`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum UpdateCollectionsV2Error {
    Status404(models::FetchAliases404Response),
    Status500(models::CreateAliases500Response),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`update_team_collections`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum UpdateTeamCollectionsError {
    Status404(models::FetchAliases404Response),
    Status500(models::CreateAliases500Response),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`update_team_collections_v2`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum UpdateTeamCollectionsV2Error {
    Status404(models::FetchAliases404Response),
    Status500(models::CreateAliases500Response),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`update_user_collections_v2`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum UpdateUserCollectionsV2Error {
    Status404(models::FetchAliases404Response),
    Status500(models::CreateAliases500Response),
    UnknownValue(serde_json::Value),
}


/// Get user counts for distinct entries of a field in the model
pub async fn count_team_unique_fields_collection_v2(configuration: &configuration::Configuration, team_id: i32, field: &str) -> Result<models::CountUniqueFieldsCollections200Response, Error<CountTeamUniqueFieldsCollectionV2Error>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_team_id = team_id;
    let p_path_field = field;

    let uri_str = format!("{}/api/v2/teams/{teamId}/collections/count/{field}", configuration.base_path, teamId=p_path_team_id, field=crate::apis::urlencode(p_path_field));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::CountUniqueFieldsCollections200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::CountUniqueFieldsCollections200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<CountTeamUniqueFieldsCollectionV2Error> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Get Counts for distinct entries of a field in the model
#[deprecated]
pub async fn count_unique_fields_collections(configuration: &configuration::Configuration, field: &str, team_id: i32, user_id: i32) -> Result<models::CountUniqueFieldsCollections200Response, Error<CountUniqueFieldsCollectionsError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_field = field;
    let p_query_team_id = team_id;
    let p_query_user_id = user_id;

    let uri_str = format!("{}/api/v1/collections/count/{field}", configuration.base_path, field=crate::apis::urlencode(p_path_field));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    req_builder = req_builder.query(&[("team_id", &p_query_team_id.to_string())]);
    req_builder = req_builder.query(&[("user_id", &p_query_user_id.to_string())]);
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::CountUniqueFieldsCollections200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::CountUniqueFieldsCollections200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<CountUniqueFieldsCollectionsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Get Counts for distinct entries of a field in the model
pub async fn count_unique_fields_collections_v2(configuration: &configuration::Configuration, field: &str) -> Result<models::CountUniqueFieldsCollections200Response, Error<CountUniqueFieldsCollectionsV2Error>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_field = field;

    let uri_str = format!("{}/api/v2/collections/count/{field}", configuration.base_path, field=crate::apis::urlencode(p_path_field));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::CountUniqueFieldsCollections200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::CountUniqueFieldsCollections200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<CountUniqueFieldsCollectionsV2Error> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Get user counts for distinct entries of a field in the model
pub async fn count_user_unique_fields_collection_v2(configuration: &configuration::Configuration, user_id: i32, field: &str) -> Result<models::CountUniqueFieldsCollections200Response, Error<CountUserUniqueFieldsCollectionV2Error>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_user_id = user_id;
    let p_path_field = field;

    let uri_str = format!("{}/api/v2/users/{userId}/collections/count/{field}", configuration.base_path, userId=p_path_user_id, field=crate::apis::urlencode(p_path_field));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::CountUniqueFieldsCollections200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::CountUniqueFieldsCollections200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<CountUserUniqueFieldsCollectionV2Error> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Create a new collection owned by an individual
pub async fn create_collections(configuration: &configuration::Configuration, create_collections_request: models::CreateCollectionsRequest) -> Result<models::CreateCategories200Response, Error<CreateCollectionsError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_body_create_collections_request = create_collections_request;

    let uri_str = format!("{}/api/v2/collections", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&p_body_create_collections_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::CreateCategories200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::CreateCategories200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<CreateCollectionsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Create a new collection for a team
#[deprecated]
pub async fn create_team_collections(configuration: &configuration::Configuration, team_id: i32, create_team_collections_request: models::CreateTeamCollectionsRequest) -> Result<models::CreateCategories200Response, Error<CreateTeamCollectionsError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_team_id = team_id;
    let p_body_create_team_collections_request = create_team_collections_request;

    let uri_str = format!("{}/api/v1/teams/{teamId}/collections", configuration.base_path, teamId=p_path_team_id);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&p_body_create_team_collections_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::CreateCategories200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::CreateCategories200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<CreateTeamCollectionsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Create a new collection for a team
pub async fn create_team_collections_v2(configuration: &configuration::Configuration, team_id: i32, create_team_collections_request: models::CreateTeamCollectionsRequest) -> Result<models::CreateCategories200Response, Error<CreateTeamCollectionsV2Error>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_team_id = team_id;
    let p_body_create_team_collections_request = create_team_collections_request;

    let uri_str = format!("{}/api/v2/teams/{teamId}/collections", configuration.base_path, teamId=p_path_team_id);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&p_body_create_team_collections_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::CreateCategories200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::CreateCategories200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<CreateTeamCollectionsV2Error> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Create a new collection owned by an individual
pub async fn create_user_collections(configuration: &configuration::Configuration, create_collections_request: models::CreateCollectionsRequest) -> Result<models::CreateCategories200Response, Error<CreateUserCollectionsError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_body_create_collections_request = create_collections_request;

    let uri_str = format!("{}/api/v2/users/collections", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&p_body_create_collections_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::CreateCategories200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::CreateCategories200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<CreateUserCollectionsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Delete a collection
pub async fn delete_collections_v2(configuration: &configuration::Configuration, id: i32) -> Result<models::DeleteAliases200Response, Error<DeleteCollectionsV2Error>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_id = id;

    let uri_str = format!("{}/api/v2/collections/{id}", configuration.base_path, id=p_path_id);
    let mut req_builder = configuration.client.request(reqwest::Method::DELETE, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::DeleteAliases200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::DeleteAliases200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<DeleteCollectionsV2Error> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Delete a collection owned by a team
#[deprecated]
pub async fn delete_team_collections(configuration: &configuration::Configuration, team_id: i32, id: i32) -> Result<models::DeleteAliases200Response, Error<DeleteTeamCollectionsError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_team_id = team_id;
    let p_path_id = id;

    let uri_str = format!("{}/api/v1/teams/{teamId}/collections/{id}", configuration.base_path, teamId=p_path_team_id, id=p_path_id);
    let mut req_builder = configuration.client.request(reqwest::Method::DELETE, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::DeleteAliases200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::DeleteAliases200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<DeleteTeamCollectionsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Delete a collection owned by a team
pub async fn delete_team_collections_v2(configuration: &configuration::Configuration, team_id: i32, id: i32) -> Result<models::DeleteAliases200Response, Error<DeleteTeamCollectionsV2Error>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_team_id = team_id;
    let p_path_id = id;

    let uri_str = format!("{}/api/v2/teams/{teamId}/collections/{id}", configuration.base_path, teamId=p_path_team_id, id=p_path_id);
    let mut req_builder = configuration.client.request(reqwest::Method::DELETE, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::DeleteAliases200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::DeleteAliases200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<DeleteTeamCollectionsV2Error> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Delete a collection
pub async fn delete_user_collections_v2(configuration: &configuration::Configuration, user_id: i32, id: i32) -> Result<models::DeleteAliases200Response, Error<DeleteUserCollectionsV2Error>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_user_id = user_id;
    let p_path_id = id;

    let uri_str = format!("{}/api/v2/users/{userId}/collections/{id}", configuration.base_path, userId=p_path_user_id, id=p_path_id);
    let mut req_builder = configuration.client.request(reqwest::Method::DELETE, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::DeleteAliases200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::DeleteAliases200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<DeleteUserCollectionsV2Error> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Edit a collection
pub async fn edit_collections_v2(configuration: &configuration::Configuration, id: i32, edit_collections_v2_request: models::EditCollectionsV2Request, unarchive: Option<&str>) -> Result<models::FetchCollections200Response, Error<EditCollectionsV2Error>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_id = id;
    let p_body_edit_collections_v2_request = edit_collections_v2_request;
    let p_query_unarchive = unarchive;

    let uri_str = format!("{}/api/v2/collections/{id}", configuration.base_path, id=p_path_id);
    let mut req_builder = configuration.client.request(reqwest::Method::PATCH, &uri_str);

    if let Some(ref param_value) = p_query_unarchive {
        req_builder = req_builder.query(&[("unarchive", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&p_body_edit_collections_v2_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::FetchCollections200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::FetchCollections200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<EditCollectionsV2Error> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Edit a collection owned by a team
#[deprecated]
pub async fn edit_team_collections(configuration: &configuration::Configuration, team_id: i32, id: i32, edit_team_collections_request: models::EditTeamCollectionsRequest, unarchive: Option<&str>) -> Result<models::FetchCollections200Response, Error<EditTeamCollectionsError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_team_id = team_id;
    let p_path_id = id;
    let p_body_edit_team_collections_request = edit_team_collections_request;
    let p_query_unarchive = unarchive;

    let uri_str = format!("{}/api/v1/teams/{teamId}/collections/{id}", configuration.base_path, teamId=p_path_team_id, id=p_path_id);
    let mut req_builder = configuration.client.request(reqwest::Method::PATCH, &uri_str);

    if let Some(ref param_value) = p_query_unarchive {
        req_builder = req_builder.query(&[("unarchive", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&p_body_edit_team_collections_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::FetchCollections200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::FetchCollections200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<EditTeamCollectionsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Edit a collection owned by a team
pub async fn edit_team_collections_v2(configuration: &configuration::Configuration, team_id: i32, id: i32, edit_team_collections_request: models::EditTeamCollectionsRequest) -> Result<models::FetchCollections200Response, Error<EditTeamCollectionsV2Error>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_team_id = team_id;
    let p_path_id = id;
    let p_body_edit_team_collections_request = edit_team_collections_request;

    let uri_str = format!("{}/api/v2/teams/{teamId}/collections/{id}", configuration.base_path, teamId=p_path_team_id, id=p_path_id);
    let mut req_builder = configuration.client.request(reqwest::Method::PATCH, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&p_body_edit_team_collections_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::FetchCollections200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::FetchCollections200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<EditTeamCollectionsV2Error> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Edit a collection
pub async fn edit_user_collections_v2(configuration: &configuration::Configuration, user_id: i32, id: i32, edit_collections_v2_request: models::EditCollectionsV2Request) -> Result<models::FetchCollections200Response, Error<EditUserCollectionsV2Error>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_user_id = user_id;
    let p_path_id = id;
    let p_body_edit_collections_v2_request = edit_collections_v2_request;

    let uri_str = format!("{}/api/v2/users/{userId}/collections/{id}", configuration.base_path, userId=p_path_user_id, id=p_path_id);
    let mut req_builder = configuration.client.request(reqwest::Method::PATCH, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&p_body_edit_collections_v2_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::FetchCollections200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::FetchCollections200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<EditUserCollectionsV2Error> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Returns a list of collections
#[deprecated]
pub async fn fetch_all_collections(configuration: &configuration::Configuration, name: Option<&str>, team_id: Option<i32>, user_id: Option<i32>, title: Option<&str>, status: Option<&str>, per_page: Option<i32>) -> Result<models::FetchAllCollections200Response, Error<FetchAllCollectionsError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_name = name;
    let p_query_team_id = team_id;
    let p_query_user_id = user_id;
    let p_query_title = title;
    let p_query_status = status;
    let p_query_per_page = per_page;

    let uri_str = format!("{}/api/v1/collections", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_name {
        req_builder = req_builder.query(&[("name", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_team_id {
        req_builder = req_builder.query(&[("team_id", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_user_id {
        req_builder = req_builder.query(&[("user_id", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_title {
        req_builder = req_builder.query(&[("title", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_status {
        req_builder = req_builder.query(&[("status", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_per_page {
        req_builder = req_builder.query(&[("per_page", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::FetchAllCollections200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::FetchAllCollections200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<FetchAllCollectionsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Returns a list of collections
pub async fn fetch_all_collections_v2(configuration: &configuration::Configuration, ) -> Result<models::FetchAllCollections200Response, Error<FetchAllCollectionsV2Error>> {

    let uri_str = format!("{}/api/v2/collections", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::FetchAllCollections200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::FetchAllCollections200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<FetchAllCollectionsV2Error> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Get collection by id
#[deprecated]
pub async fn fetch_collections(configuration: &configuration::Configuration, id: i32, view_type: Option<&str>) -> Result<models::FetchCollections200Response, Error<FetchCollectionsError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_id = id;
    let p_query_view_type = view_type;

    let uri_str = format!("{}/api/v1/collections/{id}", configuration.base_path, id=p_path_id);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_view_type {
        req_builder = req_builder.query(&[("view_type", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::FetchCollections200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::FetchCollections200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<FetchCollectionsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Get collection by id
pub async fn fetch_collections_v2(configuration: &configuration::Configuration, id: i32, view_type: Option<&str>) -> Result<models::FetchCollections200Response, Error<FetchCollectionsV2Error>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_id = id;
    let p_query_view_type = view_type;

    let uri_str = format!("{}/api/v2/collections/{id}", configuration.base_path, id=p_path_id);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_view_type {
        req_builder = req_builder.query(&[("view_type", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::FetchCollections200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::FetchCollections200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<FetchCollectionsV2Error> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Returns a list of a teams collections
pub async fn fetch_team_active_collections_v2(configuration: &configuration::Configuration, team_id: i32) -> Result<models::FetchAllCollections200Response, Error<FetchTeamActiveCollectionsV2Error>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_team_id = team_id;

    let uri_str = format!("{}/api/v2/teams/{teamId}/collections/status/active", configuration.base_path, teamId=p_path_team_id);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::FetchAllCollections200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::FetchAllCollections200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<FetchTeamActiveCollectionsV2Error> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Returns a list of a teams archived collections
pub async fn fetch_team_archived_collections_v2(configuration: &configuration::Configuration, team_id: i32) -> Result<models::FetchAllCollections200Response, Error<FetchTeamArchivedCollectionsV2Error>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_team_id = team_id;

    let uri_str = format!("{}/api/v2/teams/{teamId}/collections/status/archived", configuration.base_path, teamId=p_path_team_id);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::FetchAllCollections200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::FetchAllCollections200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<FetchTeamArchivedCollectionsV2Error> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Get collection by id
pub async fn fetch_team_collection_v2(configuration: &configuration::Configuration, team_id: i32, id: i32) -> Result<models::FetchCollections200Response, Error<FetchTeamCollectionV2Error>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_team_id = team_id;
    let p_path_id = id;

    let uri_str = format!("{}/api/v2/teams/{teamId}/collections/{id}", configuration.base_path, teamId=p_path_team_id, id=p_path_id);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::FetchCollections200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::FetchCollections200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<FetchTeamCollectionV2Error> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Returns a list of a teams draft collections
pub async fn fetch_team_draft_collections_v2(configuration: &configuration::Configuration, team_id: i32) -> Result<models::FetchAllCollections200Response, Error<FetchTeamDraftCollectionsV2Error>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_team_id = team_id;

    let uri_str = format!("{}/api/v2/teams/{teamId}/collections/status/draft", configuration.base_path, teamId=p_path_team_id);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::FetchAllCollections200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::FetchAllCollections200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<FetchTeamDraftCollectionsV2Error> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Returns a list of a users archived collections
pub async fn fetch_user_archived_collections_v2(configuration: &configuration::Configuration, user_id: i32) -> Result<models::FetchAllCollections200Response, Error<FetchUserArchivedCollectionsV2Error>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_user_id = user_id;

    let uri_str = format!("{}/api/v2/users/{userId}/collections/status/archived", configuration.base_path, userId=p_path_user_id);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::FetchAllCollections200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::FetchAllCollections200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<FetchUserArchivedCollectionsV2Error> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Get collection by id
pub async fn fetch_user_collection_v2(configuration: &configuration::Configuration, user_id: i32, id: i32) -> Result<models::FetchCollections200Response, Error<FetchUserCollectionV2Error>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_user_id = user_id;
    let p_path_id = id;

    let uri_str = format!("{}/api/v2/users/{userId}/collections/{id}", configuration.base_path, userId=p_path_user_id, id=p_path_id);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::FetchCollections200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::FetchCollections200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<FetchUserCollectionV2Error> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Returns a list of a users collections
pub async fn fetch_user_collections_v2(configuration: &configuration::Configuration, user_id: i32) -> Result<models::FetchAllCollections200Response, Error<FetchUserCollectionsV2Error>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_user_id = user_id;

    let uri_str = format!("{}/api/v2/users/{userId}/collections/status/active", configuration.base_path, userId=p_path_user_id);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::FetchAllCollections200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::FetchAllCollections200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<FetchUserCollectionsV2Error> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Returns a list of a users draft collections
pub async fn fetch_user_draft_collections_v2(configuration: &configuration::Configuration, user_id: i32) -> Result<models::FetchAllCollections200Response, Error<FetchUserDraftCollectionsV2Error>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_user_id = user_id;

    let uri_str = format!("{}/api/v2/users/{userId}/collections/status/draft", configuration.base_path, userId=p_path_user_id);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::FetchAllCollections200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::FetchAllCollections200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<FetchUserDraftCollectionsV2Error> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Update a collection owned by an individual
pub async fn update_collections_v2(configuration: &configuration::Configuration, id: i32, update_collections_v2_request: models::UpdateCollectionsV2Request) -> Result<models::FetchCollections200Response, Error<UpdateCollectionsV2Error>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_id = id;
    let p_body_update_collections_v2_request = update_collections_v2_request;

    let uri_str = format!("{}/api/v2/collections/{id}", configuration.base_path, id=p_path_id);
    let mut req_builder = configuration.client.request(reqwest::Method::PUT, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&p_body_update_collections_v2_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::FetchCollections200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::FetchCollections200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<UpdateCollectionsV2Error> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Update a collection owned by a team
#[deprecated]
pub async fn update_team_collections(configuration: &configuration::Configuration, team_id: i32, id: i32, update_team_collections_request: models::UpdateTeamCollectionsRequest) -> Result<models::FetchCollections200Response, Error<UpdateTeamCollectionsError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_team_id = team_id;
    let p_path_id = id;
    let p_body_update_team_collections_request = update_team_collections_request;

    let uri_str = format!("{}/api/v1/teams/{teamId}/collections/{id}", configuration.base_path, teamId=p_path_team_id, id=p_path_id);
    let mut req_builder = configuration.client.request(reqwest::Method::PUT, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&p_body_update_team_collections_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::FetchCollections200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::FetchCollections200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<UpdateTeamCollectionsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Update a collection owned by a team
pub async fn update_team_collections_v2(configuration: &configuration::Configuration, team_id: i32, id: i32, update_team_collections_request: models::UpdateTeamCollectionsRequest) -> Result<models::FetchCollections200Response, Error<UpdateTeamCollectionsV2Error>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_team_id = team_id;
    let p_path_id = id;
    let p_body_update_team_collections_request = update_team_collections_request;

    let uri_str = format!("{}/api/v2/teams/{teamId}/collections/{id}", configuration.base_path, teamId=p_path_team_id, id=p_path_id);
    let mut req_builder = configuration.client.request(reqwest::Method::PUT, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&p_body_update_team_collections_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::FetchCollections200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::FetchCollections200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<UpdateTeamCollectionsV2Error> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Update a collection owned by an individual
pub async fn update_user_collections_v2(configuration: &configuration::Configuration, user_id: i32, id: i32, update_collections_v2_request: models::UpdateCollectionsV2Request) -> Result<models::FetchCollections200Response, Error<UpdateUserCollectionsV2Error>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_user_id = user_id;
    let p_path_id = id;
    let p_body_update_collections_v2_request = update_collections_v2_request;

    let uri_str = format!("{}/api/v2/users/{userId}/collections/{id}", configuration.base_path, userId=p_path_user_id, id=p_path_id);
    let mut req_builder = configuration.client.request(reqwest::Method::PUT, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&p_body_update_collections_v2_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::FetchCollections200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::FetchCollections200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<UpdateUserCollectionsV2Error> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

