/*
 * HDRUK Gateway API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};


/// struct for typed errors of method [`delete_team_dar_application_file`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DeleteTeamDarApplicationFileError {
    Status404(models::UpdateApplications404Response),
    Status500(models::CreateApplications500Response),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`fetch_team_dar_application_answers`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum FetchTeamDarApplicationAnswersError {
    Status404(models::UpdateApplications404Response),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`fetch_team_dar_application_download_zip`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum FetchTeamDarApplicationDownloadZipError {
    Status404(models::UpdateApplications404Response),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`fetch_team_dar_application_file`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum FetchTeamDarApplicationFileError {
    Status404(models::UpdateApplications404Response),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`fetch_team_dar_application_files`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum FetchTeamDarApplicationFilesError {
    Status404(models::UpdateApplications404Response),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`fetch_team_dar_application_status_history`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum FetchTeamDarApplicationStatusHistoryError {
    Status404(models::UpdateApplications404Response),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`update_team_dar_application`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum UpdateTeamDarApplicationError {
    Status404(models::UpdateApplications404Response),
    Status500(models::CreateApplications500Response),
    UnknownValue(serde_json::Value),
}


/// Delete a file associated with a DAR application
pub async fn delete_team_dar_application_file(configuration: &configuration::Configuration, team_id: i32, id: i32, file_id: i32) -> Result<models::DeleteApplications200Response, Error<DeleteTeamDarApplicationFileError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_team_id = team_id;
    let p_path_id = id;
    let p_path_file_id = file_id;

    let uri_str = format!("{}/api/v1/teams/{teamId}/dar/applications/{id}/files/{fileId}", configuration.base_path, teamId=p_path_team_id, id=p_path_id, fileId=p_path_file_id);
    let mut req_builder = configuration.client.request(reqwest::Method::DELETE, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::DeleteApplications200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::DeleteApplications200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<DeleteTeamDarApplicationFileError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Return answers from a single DAR application
pub async fn fetch_team_dar_application_answers(configuration: &configuration::Configuration, team_id: i32, id: i32) -> Result<models::FetchTeamDarApplicationAnswers200Response, Error<FetchTeamDarApplicationAnswersError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_team_id = team_id;
    let p_path_id = id;

    let uri_str = format!("{}/api/v1/teams/{teamId}/dar/applications/{id}/answers", configuration.base_path, teamId=p_path_team_id, id=p_path_id);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::FetchTeamDarApplicationAnswers200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::FetchTeamDarApplicationAnswers200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<FetchTeamDarApplicationAnswersError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Returns a DAR form as a CSV with attached files as a zip
pub async fn fetch_team_dar_application_download_zip(configuration: &configuration::Configuration, team_id: i32, id: i32) -> Result<(), Error<FetchTeamDarApplicationDownloadZipError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_team_id = team_id;
    let p_path_id = id;

    let uri_str = format!("{}/api/v1/teams/{teamId}/dar/applications/{id}/download", configuration.base_path, teamId=p_path_team_id, id=p_path_id);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<FetchTeamDarApplicationDownloadZipError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Download a file associated with a DAR application
pub async fn fetch_team_dar_application_file(configuration: &configuration::Configuration, team_id: i32, id: i32, file_id: &str) -> Result<(), Error<FetchTeamDarApplicationFileError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_team_id = team_id;
    let p_path_id = id;
    let p_path_file_id = file_id;

    let uri_str = format!("{}/api/v1/teams/{teamId}/dar/applications/{id}/files/{fileId}/download", configuration.base_path, teamId=p_path_team_id, id=p_path_id, fileId=crate::apis::urlencode(p_path_file_id));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<FetchTeamDarApplicationFileError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Return a list of files associated with a DAR application
pub async fn fetch_team_dar_application_files(configuration: &configuration::Configuration, team_id: i32, id: i32) -> Result<models::FetchTeamDarApplicationFiles200Response, Error<FetchTeamDarApplicationFilesError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_team_id = team_id;
    let p_path_id = id;

    let uri_str = format!("{}/api/v1/teams/{teamId}/dar/applications/{id}/files", configuration.base_path, teamId=p_path_team_id, id=p_path_id);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::FetchTeamDarApplicationFiles200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::FetchTeamDarApplicationFiles200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<FetchTeamDarApplicationFilesError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Return the status history of a single DAR application
pub async fn fetch_team_dar_application_status_history(configuration: &configuration::Configuration, team_id: i32, id: i32) -> Result<models::FetchTeamDarApplicationStatusHistory200Response, Error<FetchTeamDarApplicationStatusHistoryError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_team_id = team_id;
    let p_path_id = id;

    let uri_str = format!("{}/api/v1/teams/{teamId}/dar/applications/{id}/status", configuration.base_path, teamId=p_path_team_id, id=p_path_id);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::FetchTeamDarApplicationStatusHistory200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::FetchTeamDarApplicationStatusHistory200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<FetchTeamDarApplicationStatusHistoryError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Edit a system DAR application
pub async fn update_team_dar_application(configuration: &configuration::Configuration, team_id: i32, id: i32, update_team_dar_application_request: models::UpdateTeamDarApplicationRequest) -> Result<models::FetchTeamDarApplication200Response, Error<UpdateTeamDarApplicationError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_team_id = team_id;
    let p_path_id = id;
    let p_body_update_team_dar_application_request = update_team_dar_application_request;

    let uri_str = format!("{}/api/v1/teams/{teamId}/dar/applications/{id}", configuration.base_path, teamId=p_path_team_id, id=p_path_id);
    let mut req_builder = configuration.client.request(reqwest::Method::PATCH, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&p_body_update_team_dar_application_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::FetchTeamDarApplication200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::FetchTeamDarApplication200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<UpdateTeamDarApplicationError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

