/*
 * HDRUK Gateway API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};


/// struct for typed errors of method [`create_team_dar_application_question_review`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CreateTeamDarApplicationQuestionReviewError {
    Status500(models::CreateAliases500Response),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`create_team_dar_application_review`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CreateTeamDarApplicationReviewError {
    Status500(models::CreateAliases500Response),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`delete_team_dar_application_question_review`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DeleteTeamDarApplicationQuestionReviewError {
    Status404(models::FetchAliases404Response),
    Status500(models::CreateAliases500Response),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`delete_team_dar_application_review`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DeleteTeamDarApplicationReviewError {
    Status404(models::FetchAliases404Response),
    Status500(models::CreateAliases500Response),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`delete_team_dar_application_review_file`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DeleteTeamDarApplicationReviewFileError {
    Status404(models::FetchAliases404Response),
    Status500(models::CreateAliases500Response),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`fetch_team_dar_application_review_file`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum FetchTeamDarApplicationReviewFileError {
    Status404(models::FetchAliases404Response),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`fetch_team_dar_application_reviews`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum FetchTeamDarApplicationReviewsError {
    Status404(models::FetchAliases404Response),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`fetch_user_dar_application_review_file`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum FetchUserDarApplicationReviewFileError {
    Status404(models::FetchAliases404Response),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`fetch_user_dar_application_reviews`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum FetchUserDarApplicationReviewsError {
    Status404(models::FetchAliases404Response),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`update_team_dar_application_question_review`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum UpdateTeamDarApplicationQuestionReviewError {
    Status404(models::FetchAliases404Response),
    Status500(models::CreateAliases500Response),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`update_team_dar_application_review`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum UpdateTeamDarApplicationReviewError {
    Status404(models::FetchAliases404Response),
    Status500(models::CreateAliases500Response),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`update_user_dar_application_question_review`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum UpdateUserDarApplicationQuestionReviewError {
    Status404(models::FetchAliases404Response),
    Status500(models::CreateAliases500Response),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`update_user_dar_application_review`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum UpdateUserDarApplicationReviewError {
    Status404(models::FetchAliases404Response),
    Status500(models::CreateAliases500Response),
    UnknownValue(serde_json::Value),
}


/// Create a new review comment on a question in a DAR application
pub async fn create_team_dar_application_question_review(configuration: &configuration::Configuration, team_id: i32, id: i32, question_id: i32, create_team_dar_application_review_request: models::CreateTeamDarApplicationReviewRequest) -> Result<models::CreateCategories200Response, Error<CreateTeamDarApplicationQuestionReviewError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_team_id = team_id;
    let p_path_id = id;
    let p_path_question_id = question_id;
    let p_body_create_team_dar_application_review_request = create_team_dar_application_review_request;

    let uri_str = format!("{}/api/v1/teams/{team_id}/dar/applications/{id}/questions/{questionId}/reviews", configuration.base_path, team_id=p_path_team_id, id=p_path_id, questionId=p_path_question_id);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&p_body_create_team_dar_application_review_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::CreateCategories200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::CreateCategories200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<CreateTeamDarApplicationQuestionReviewError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Create a new review comment on a DAR application
pub async fn create_team_dar_application_review(configuration: &configuration::Configuration, team_id: i32, id: i32, create_team_dar_application_review_request: models::CreateTeamDarApplicationReviewRequest) -> Result<models::CreateCategories200Response, Error<CreateTeamDarApplicationReviewError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_team_id = team_id;
    let p_path_id = id;
    let p_body_create_team_dar_application_review_request = create_team_dar_application_review_request;

    let uri_str = format!("{}/api/v1/teams/{team_id}/dar/applications/{id}/reviews", configuration.base_path, team_id=p_path_team_id, id=p_path_id);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&p_body_create_team_dar_application_review_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::CreateCategories200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::CreateCategories200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<CreateTeamDarApplicationReviewError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Delete a review from a DAR application
pub async fn delete_team_dar_application_question_review(configuration: &configuration::Configuration, team_id: i32, id: i32, question_id: i32, review_id: i32) -> Result<models::DeleteAliases200Response, Error<DeleteTeamDarApplicationQuestionReviewError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_team_id = team_id;
    let p_path_id = id;
    let p_path_question_id = question_id;
    let p_path_review_id = review_id;

    let uri_str = format!("{}/api/v1/teams/{team_id}/dar/applications/{id}/questions/{questionId}/reviews/{reviewId}", configuration.base_path, team_id=p_path_team_id, id=p_path_id, questionId=p_path_question_id, reviewId=p_path_review_id);
    let mut req_builder = configuration.client.request(reqwest::Method::DELETE, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::DeleteAliases200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::DeleteAliases200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<DeleteTeamDarApplicationQuestionReviewError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Delete a review from a DAR application
pub async fn delete_team_dar_application_review(configuration: &configuration::Configuration, team_id: i32, id: i32, review_id: i32) -> Result<models::DeleteAliases200Response, Error<DeleteTeamDarApplicationReviewError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_team_id = team_id;
    let p_path_id = id;
    let p_path_review_id = review_id;

    let uri_str = format!("{}/api/v1/teams/{team_id}/dar/applications/{id}/reviews/{reviewId}", configuration.base_path, team_id=p_path_team_id, id=p_path_id, reviewId=p_path_review_id);
    let mut req_builder = configuration.client.request(reqwest::Method::DELETE, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::DeleteAliases200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::DeleteAliases200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<DeleteTeamDarApplicationReviewError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Delete a file associated with a DAR review
pub async fn delete_team_dar_application_review_file(configuration: &configuration::Configuration, team_id: i32, id: i32, review_id: i32, file_id: &str) -> Result<models::DeleteAliases200Response, Error<DeleteTeamDarApplicationReviewFileError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_team_id = team_id;
    let p_path_id = id;
    let p_path_review_id = review_id;
    let p_path_file_id = file_id;

    let uri_str = format!("{}/api/v1/teams/{teamId}/dar/applications/{id}/reviews/{reviewId}/files/{fileId}", configuration.base_path, teamId=p_path_team_id, id=p_path_id, reviewId=p_path_review_id, fileId=crate::apis::urlencode(p_path_file_id));
    let mut req_builder = configuration.client.request(reqwest::Method::DELETE, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::DeleteAliases200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::DeleteAliases200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<DeleteTeamDarApplicationReviewFileError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Download a file associated with a DAR application review
pub async fn fetch_team_dar_application_review_file(configuration: &configuration::Configuration, team_id: i32, id: i32, review_id: i32, file_id: &str) -> Result<(), Error<FetchTeamDarApplicationReviewFileError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_team_id = team_id;
    let p_path_id = id;
    let p_path_review_id = review_id;
    let p_path_file_id = file_id;

    let uri_str = format!("{}/ap1/v1/teams/{teamId}/dar/applications/{id}/reviews/{reviewId}/download/{fileId}", configuration.base_path, teamId=p_path_team_id, id=p_path_id, reviewId=p_path_review_id, fileId=crate::apis::urlencode(p_path_file_id));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<FetchTeamDarApplicationReviewFileError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Return all reviews on a DAR application
pub async fn fetch_team_dar_application_reviews(configuration: &configuration::Configuration, team_id: i32, id: i32) -> Result<models::FetchTeamDarApplicationReviews200Response, Error<FetchTeamDarApplicationReviewsError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_team_id = team_id;
    let p_path_id = id;

    let uri_str = format!("{}/api/v1/teams/{team_id}/dar/applications/{id}/reviews", configuration.base_path, team_id=p_path_team_id, id=p_path_id);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::FetchTeamDarApplicationReviews200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::FetchTeamDarApplicationReviews200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<FetchTeamDarApplicationReviewsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Download a file associated with a DAR application review
pub async fn fetch_user_dar_application_review_file(configuration: &configuration::Configuration, user_id: i32, id: i32, review_id: i32, file_id: &str) -> Result<(), Error<FetchUserDarApplicationReviewFileError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_user_id = user_id;
    let p_path_id = id;
    let p_path_review_id = review_id;
    let p_path_file_id = file_id;

    let uri_str = format!("{}/ap1/v1/users/{userId}/dar/applications/{id}/reviews/{reviewId}/download/{fileId}", configuration.base_path, userId=p_path_user_id, id=p_path_id, reviewId=p_path_review_id, fileId=crate::apis::urlencode(p_path_file_id));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<FetchUserDarApplicationReviewFileError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Return all reviews on a DAR application
pub async fn fetch_user_dar_application_reviews(configuration: &configuration::Configuration, user_id: i32, id: i32) -> Result<models::FetchTeamDarApplicationReviews200Response, Error<FetchUserDarApplicationReviewsError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_user_id = user_id;
    let p_path_id = id;

    let uri_str = format!("{}/api/v1/users/{userId}/dar/applications/{id}/reviews", configuration.base_path, userId=p_path_user_id, id=p_path_id);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::FetchTeamDarApplicationReviews200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::FetchTeamDarApplicationReviews200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<FetchUserDarApplicationReviewsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Update a review comment on a question in a DAR application
pub async fn update_team_dar_application_question_review(configuration: &configuration::Configuration, team_id: i32, id: i32, question_id: i32, review_id: i32, create_team_dar_application_review_request: models::CreateTeamDarApplicationReviewRequest) -> Result<models::UpdateTeamDarApplicationQuestionReview200Response, Error<UpdateTeamDarApplicationQuestionReviewError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_team_id = team_id;
    let p_path_id = id;
    let p_path_question_id = question_id;
    let p_path_review_id = review_id;
    let p_body_create_team_dar_application_review_request = create_team_dar_application_review_request;

    let uri_str = format!("{}/api/v1/teams/{team_id}/dar/applications/{id}/questions/{questionId}/reviews/{reviewId}", configuration.base_path, team_id=p_path_team_id, id=p_path_id, questionId=p_path_question_id, reviewId=p_path_review_id);
    let mut req_builder = configuration.client.request(reqwest::Method::PUT, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&p_body_create_team_dar_application_review_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::UpdateTeamDarApplicationQuestionReview200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::UpdateTeamDarApplicationQuestionReview200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<UpdateTeamDarApplicationQuestionReviewError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Update a review comment on a DAR application
pub async fn update_team_dar_application_review(configuration: &configuration::Configuration, team_id: i32, id: i32, review_id: i32, create_team_dar_application_review_request: models::CreateTeamDarApplicationReviewRequest) -> Result<models::UpdateTeamDarApplicationQuestionReview200Response, Error<UpdateTeamDarApplicationReviewError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_team_id = team_id;
    let p_path_id = id;
    let p_path_review_id = review_id;
    let p_body_create_team_dar_application_review_request = create_team_dar_application_review_request;

    let uri_str = format!("{}/api/v1/teams/{team_id}/dar/applications/{id}/reviews/{reviewId}", configuration.base_path, team_id=p_path_team_id, id=p_path_id, reviewId=p_path_review_id);
    let mut req_builder = configuration.client.request(reqwest::Method::PUT, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&p_body_create_team_dar_application_review_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::UpdateTeamDarApplicationQuestionReview200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::UpdateTeamDarApplicationQuestionReview200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<UpdateTeamDarApplicationReviewError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// User endpoint to update a review comment on a question in a DAR application
pub async fn update_user_dar_application_question_review(configuration: &configuration::Configuration, user_id: i32, id: i32, question_id: i32, review_id: i32, create_team_dar_application_review_request: models::CreateTeamDarApplicationReviewRequest) -> Result<models::UpdateTeamDarApplicationQuestionReview200Response, Error<UpdateUserDarApplicationQuestionReviewError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_user_id = user_id;
    let p_path_id = id;
    let p_path_question_id = question_id;
    let p_path_review_id = review_id;
    let p_body_create_team_dar_application_review_request = create_team_dar_application_review_request;

    let uri_str = format!("{}/api/v1/users/{userId}/dar/applications/{id}/questions/{questionId}/reviews/{reviewId}", configuration.base_path, userId=p_path_user_id, id=p_path_id, questionId=p_path_question_id, reviewId=p_path_review_id);
    let mut req_builder = configuration.client.request(reqwest::Method::PUT, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&p_body_create_team_dar_application_review_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::UpdateTeamDarApplicationQuestionReview200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::UpdateTeamDarApplicationQuestionReview200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<UpdateUserDarApplicationQuestionReviewError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// User endpoint to update a review comment on a DAR application
pub async fn update_user_dar_application_review(configuration: &configuration::Configuration, user_id: i32, id: i32, review_id: i32, create_team_dar_application_review_request: models::CreateTeamDarApplicationReviewRequest) -> Result<models::UpdateTeamDarApplicationQuestionReview200Response, Error<UpdateUserDarApplicationReviewError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_user_id = user_id;
    let p_path_id = id;
    let p_path_review_id = review_id;
    let p_body_create_team_dar_application_review_request = create_team_dar_application_review_request;

    let uri_str = format!("{}/api/v1/users/{userId}/dar/applications/{id}/reviews/{reviewId}", configuration.base_path, userId=p_path_user_id, id=p_path_id, reviewId=p_path_review_id);
    let mut req_builder = configuration.client.request(reqwest::Method::PUT, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&p_body_create_team_dar_application_review_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::UpdateTeamDarApplicationQuestionReview200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::UpdateTeamDarApplicationQuestionReview200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<UpdateUserDarApplicationReviewError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

