/*
 * HDRUK Gateway API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};


/// struct for typed errors of method [`count_unique_fields_publications`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CountUniqueFieldsPublicationsError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`create_publications`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CreatePublicationsError {
    Status401(models::FetchAllDarIntegrations401Response),
    Status500(models::CreateApplications500Response),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`delete_publications`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DeletePublicationsError {
    Status401(models::FetchAllDarIntegrations401Response),
    Status404(models::DeleteFederation404Response),
    Status500(models::CreateApplications500Response),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`edit_publications`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum EditPublicationsError {
    Status400(models::CreateToolsIntegrations400Response),
    Status401(models::FetchAllDarIntegrations401Response),
    Status500(models::CreateApplications500Response),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`fetch_all_publications`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum FetchAllPublicationsError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`fetch_all_publications_v2`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum FetchAllPublicationsV2Error {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`fetch_publications`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum FetchPublicationsError {
    Status401(models::FetchAllDarIntegrations401Response),
    Status404(models::UpdateApplications404Response),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`fetch_publications_v2`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum FetchPublicationsV2Error {
    Status401(models::FetchAllDarIntegrations401Response),
    Status404(models::UpdateApplications404Response),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`update_publications`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum UpdatePublicationsError {
    Status400(models::CreateToolsIntegrations400Response),
    Status401(models::FetchAllDarIntegrations401Response),
    Status500(models::CreateApplications500Response),
    UnknownValue(serde_json::Value),
}


/// Get Counts for distinct entries of a field in the model
#[deprecated]
pub async fn count_unique_fields_publications(configuration: &configuration::Configuration, field: &str, owner_id: i32, team_id: Option<i32>) -> Result<models::CountUniqueFieldsCollections200Response, Error<CountUniqueFieldsPublicationsError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_field = field;
    let p_query_owner_id = owner_id;
    let p_query_team_id = team_id;

    let uri_str = format!("{}/api/v1/publication/count/{field}", configuration.base_path, field=crate::apis::urlencode(p_path_field));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    req_builder = req_builder.query(&[("owner_id", &p_query_owner_id.to_string())]);
    if let Some(ref param_value) = p_query_team_id {
        req_builder = req_builder.query(&[("team_id", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::CountUniqueFieldsCollections200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::CountUniqueFieldsCollections200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<CountUniqueFieldsPublicationsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Create a new publication
#[deprecated]
pub async fn create_publications(configuration: &configuration::Configuration, create_publications_request: models::CreatePublicationsRequest) -> Result<models::CreateDarIntegration201Response, Error<CreatePublicationsError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_body_create_publications_request = create_publications_request;

    let uri_str = format!("{}/api/v1/publications", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&p_body_create_publications_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::CreateDarIntegration201Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::CreateDarIntegration201Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<CreatePublicationsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Delete publication by id
#[deprecated]
pub async fn delete_publications(configuration: &configuration::Configuration, id: i32) -> Result<models::DeleteFederation200Response, Error<DeletePublicationsError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_id = id;

    let uri_str = format!("{}/api/v1/publications/{id}", configuration.base_path, id=p_path_id);
    let mut req_builder = configuration.client.request(reqwest::Method::DELETE, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::DeleteFederation200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::DeleteFederation200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<DeletePublicationsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Edit publications
#[deprecated]
pub async fn edit_publications(configuration: &configuration::Configuration, id: i32, update_publications_request: models::UpdatePublicationsRequest, unarchive: Option<&str>) -> Result<models::FetchPublications200Response, Error<EditPublicationsError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_id = id;
    let p_body_update_publications_request = update_publications_request;
    let p_query_unarchive = unarchive;

    let uri_str = format!("{}/api/v1/publications/{id}", configuration.base_path, id=p_path_id);
    let mut req_builder = configuration.client.request(reqwest::Method::PATCH, &uri_str);

    if let Some(ref param_value) = p_query_unarchive {
        req_builder = req_builder.query(&[("unarchive", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&p_body_update_publications_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::FetchPublications200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::FetchPublications200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<EditPublicationsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Get All Publications
#[deprecated]
pub async fn fetch_all_publications(configuration: &configuration::Configuration, paper_title: Option<&str>, owner_id: Option<models::models::Int>, team_id: Option<models::models::Int>, status: Option<&str>) -> Result<models::FetchAllPublications200Response, Error<FetchAllPublicationsError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_paper_title = paper_title;
    let p_query_owner_id = owner_id;
    let p_query_team_id = team_id;
    let p_query_status = status;

    let uri_str = format!("{}/api/v1/publications", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_paper_title {
        req_builder = req_builder.query(&[("paper_title", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_owner_id {
        req_builder = req_builder.query(&[("owner_id", &serde_json::to_string(param_value)?)]);
    }
    if let Some(ref param_value) = p_query_team_id {
        req_builder = req_builder.query(&[("team_id", &serde_json::to_string(param_value)?)]);
    }
    if let Some(ref param_value) = p_query_status {
        req_builder = req_builder.query(&[("status", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::FetchAllPublications200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::FetchAllPublications200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<FetchAllPublicationsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Get All Publications
pub async fn fetch_all_publications_v2(configuration: &configuration::Configuration, paper_title: Option<&str>, with_related: Option<bool>, per_page: Option<i32>) -> Result<models::FetchAllPublications200Response, Error<FetchAllPublicationsV2Error>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_paper_title = paper_title;
    let p_query_with_related = with_related;
    let p_query_per_page = per_page;

    let uri_str = format!("{}/api/v2/publications", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_paper_title {
        req_builder = req_builder.query(&[("paper_title", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_with_related {
        req_builder = req_builder.query(&[("with_related", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_per_page {
        req_builder = req_builder.query(&[("per_page", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::FetchAllPublications200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::FetchAllPublications200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<FetchAllPublicationsV2Error> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Get publication by id
#[deprecated]
pub async fn fetch_publications(configuration: &configuration::Configuration, id: i32) -> Result<models::FetchPublications200Response, Error<FetchPublicationsError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_id = id;

    let uri_str = format!("{}/api/v1/publications/{id}", configuration.base_path, id=p_path_id);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::FetchPublications200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::FetchPublications200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<FetchPublicationsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Get publication by id
pub async fn fetch_publications_v2(configuration: &configuration::Configuration, id: i32) -> Result<models::FetchPublications200Response, Error<FetchPublicationsV2Error>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_id = id;

    let uri_str = format!("{}/api/v2/publications/{id}", configuration.base_path, id=p_path_id);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::FetchPublications200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::FetchPublications200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<FetchPublicationsV2Error> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Update publications
#[deprecated]
pub async fn update_publications(configuration: &configuration::Configuration, id: i32, update_publications_request: models::UpdatePublicationsRequest) -> Result<models::FetchPublications200Response, Error<UpdatePublicationsError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_id = id;
    let p_body_update_publications_request = update_publications_request;

    let uri_str = format!("{}/api/v1/publications/{id}", configuration.base_path, id=p_path_id);
    let mut req_builder = configuration.client.request(reqwest::Method::PUT, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&p_body_update_publications_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::FetchPublications200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::FetchPublications200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<UpdatePublicationsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

