/*
 * HDRUK Gateway API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};


/// struct for typed errors of method [`create_question_bank_question`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CreateQuestionBankQuestionError {
    Status500(models::CreateAliases500Response),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`delete_question_bank_question`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DeleteQuestionBankQuestionError {
    Status404(models::FetchAliases404Response),
    Status500(models::CreateAliases500Response),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`download_question_bank_question_file`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DownloadQuestionBankQuestionFileError {
    Status404(models::FetchAliases404Response),
    Status500(models::CreateAliases500Response),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`edit_question_bank_question`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum EditQuestionBankQuestionError {
    Status404(models::FetchAliases404Response),
    Status500(models::CreateAliases500Response),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`fetch_archived_question_bank_questions`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum FetchArchivedQuestionBankQuestionsError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`fetch_custom_question_bank_questions`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum FetchCustomQuestionBankQuestionsError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`fetch_question_bank_question`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum FetchQuestionBankQuestionError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`fetch_question_bank_question_version`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum FetchQuestionBankQuestionVersionError {
    Status404(models::FetchAliases404Response),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`fetch_question_bank_questions`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum FetchQuestionBankQuestionsError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`fetch_standard_question_bank_questions`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum FetchStandardQuestionBankQuestionsError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`fetch_team_question_bank_questions_by_section`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum FetchTeamQuestionBankQuestionsBySectionError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`update_question_bank_question`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum UpdateQuestionBankQuestionError {
    Status404(models::FetchAliases404Response),
    Status500(models::CreateAliases500Response),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`update_question_bank_question_status`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum UpdateQuestionBankQuestionStatusError {
    Status404(models::FetchAliases404Response),
    Status500(models::CreateAliases500Response),
    UnknownValue(serde_json::Value),
}


/// Create a new system question bank question with FE-helpful input format
pub async fn create_question_bank_question(configuration: &configuration::Configuration, create_question_bank_question_request: models::CreateQuestionBankQuestionRequest) -> Result<models::CreateCategories200Response, Error<CreateQuestionBankQuestionError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_body_create_question_bank_question_request = create_question_bank_question_request;

    let uri_str = format!("{}/api/v1/questions", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&p_body_create_question_bank_question_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::CreateCategories200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::CreateCategories200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<CreateQuestionBankQuestionError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Delete a system question bank question
pub async fn delete_question_bank_question(configuration: &configuration::Configuration, id: i32) -> Result<models::DeleteAliases200Response, Error<DeleteQuestionBankQuestionError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_id = id;

    let uri_str = format!("{}/api/v1/questions/{id}", configuration.base_path, id=p_path_id);
    let mut req_builder = configuration.client.request(reqwest::Method::DELETE, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::DeleteAliases200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::DeleteAliases200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<DeleteQuestionBankQuestionError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Download a system question bank question
pub async fn download_question_bank_question_file(configuration: &configuration::Configuration, id: i32, file_id: i32) -> Result<models::DeleteAliases200Response, Error<DownloadQuestionBankQuestionFileError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_id = id;
    let p_path_file_id = file_id;

    let uri_str = format!("{}/api/v1/questions/{id}/files/{fileId}", configuration.base_path, id=p_path_id, fileId=p_path_file_id);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::DeleteAliases200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::DeleteAliases200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<DownloadQuestionBankQuestionFileError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Edit a system question bank question - use this for parents and children separately
pub async fn edit_question_bank_question(configuration: &configuration::Configuration, id: i32, edit_question_bank_question_request: models::EditQuestionBankQuestionRequest) -> Result<models::UpdateQuestionBankQuestion200Response, Error<EditQuestionBankQuestionError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_id = id;
    let p_body_edit_question_bank_question_request = edit_question_bank_question_request;

    let uri_str = format!("{}/api/v1/questions/{id}", configuration.base_path, id=p_path_id);
    let mut req_builder = configuration.client.request(reqwest::Method::PATCH, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&p_body_edit_question_bank_question_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::UpdateQuestionBankQuestion200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::UpdateQuestionBankQuestion200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<EditQuestionBankQuestionError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// List of archived question bank questions
pub async fn fetch_archived_question_bank_questions(configuration: &configuration::Configuration, section_id: Option<i32>, is_child: Option<i32>, per_page: Option<i32>, page: Option<i32>) -> Result<models::FetchQuestionBankQuestions200Response, Error<FetchArchivedQuestionBankQuestionsError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_section_id = section_id;
    let p_query_is_child = is_child;
    let p_query_per_page = per_page;
    let p_query_page = page;

    let uri_str = format!("{}/api/v1/questions/archived", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_section_id {
        req_builder = req_builder.query(&[("section_id", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_is_child {
        req_builder = req_builder.query(&[("is_child", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_per_page {
        req_builder = req_builder.query(&[("per_page", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_page {
        req_builder = req_builder.query(&[("page", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::FetchQuestionBankQuestions200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::FetchQuestionBankQuestions200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<FetchArchivedQuestionBankQuestionsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// List of custom question bank questions
pub async fn fetch_custom_question_bank_questions(configuration: &configuration::Configuration, section_id: Option<i32>, is_child: Option<i32>, per_page: Option<i32>, page: Option<i32>) -> Result<models::FetchCustomQuestionBankQuestions200Response, Error<FetchCustomQuestionBankQuestionsError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_section_id = section_id;
    let p_query_is_child = is_child;
    let p_query_per_page = per_page;
    let p_query_page = page;

    let uri_str = format!("{}/api/v1/questions/custom", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_section_id {
        req_builder = req_builder.query(&[("section_id", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_is_child {
        req_builder = req_builder.query(&[("is_child", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_per_page {
        req_builder = req_builder.query(&[("per_page", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_page {
        req_builder = req_builder.query(&[("page", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::FetchCustomQuestionBankQuestions200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::FetchCustomQuestionBankQuestions200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<FetchCustomQuestionBankQuestionsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Return the latest question bank question version for the supplied question id, in an FE-friendly format
pub async fn fetch_question_bank_question(configuration: &configuration::Configuration, id: i32) -> Result<models::FetchQuestionBankQuestion200Response, Error<FetchQuestionBankQuestionError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_id = id;

    let uri_str = format!("{}/api/v1/questions/{id}", configuration.base_path, id=p_path_id);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::FetchQuestionBankQuestion200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::FetchQuestionBankQuestion200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<FetchQuestionBankQuestionError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Return a single system question bank question version
pub async fn fetch_question_bank_question_version(configuration: &configuration::Configuration, id: i32) -> Result<models::FetchQuestionBankQuestionVersion200Response, Error<FetchQuestionBankQuestionVersionError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_id = id;

    let uri_str = format!("{}/api/v1/questions/version/{id}", configuration.base_path, id=p_path_id);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::FetchQuestionBankQuestionVersion200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::FetchQuestionBankQuestionVersion200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<FetchQuestionBankQuestionVersionError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// List of question bank questions
pub async fn fetch_question_bank_questions(configuration: &configuration::Configuration, section_id: Option<i32>, is_child: Option<i32>, per_page: Option<i32>, page: Option<i32>) -> Result<models::FetchQuestionBankQuestions200Response, Error<FetchQuestionBankQuestionsError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_section_id = section_id;
    let p_query_is_child = is_child;
    let p_query_per_page = per_page;
    let p_query_page = page;

    let uri_str = format!("{}/api/v1/questions", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_section_id {
        req_builder = req_builder.query(&[("section_id", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_is_child {
        req_builder = req_builder.query(&[("is_child", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_per_page {
        req_builder = req_builder.query(&[("per_page", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_page {
        req_builder = req_builder.query(&[("page", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::FetchQuestionBankQuestions200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::FetchQuestionBankQuestions200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<FetchQuestionBankQuestionsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// List of standard question bank questions
pub async fn fetch_standard_question_bank_questions(configuration: &configuration::Configuration, section_id: Option<i32>, is_child: Option<i32>, per_page: Option<i32>, page: Option<i32>) -> Result<models::FetchStandardQuestionBankQuestions200Response, Error<FetchStandardQuestionBankQuestionsError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_section_id = section_id;
    let p_query_is_child = is_child;
    let p_query_per_page = per_page;
    let p_query_page = page;

    let uri_str = format!("{}/api/v1/questions/standard", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_section_id {
        req_builder = req_builder.query(&[("section_id", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_is_child {
        req_builder = req_builder.query(&[("is_child", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_per_page {
        req_builder = req_builder.query(&[("per_page", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_page {
        req_builder = req_builder.query(&[("page", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::FetchStandardQuestionBankQuestions200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::FetchStandardQuestionBankQuestions200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<FetchStandardQuestionBankQuestionsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// List of question bank questions by section
pub async fn fetch_team_question_bank_questions_by_section(configuration: &configuration::Configuration, team_id: i32, section_id: i32, is_child: Option<i32>) -> Result<models::FetchTeamQuestionBankQuestionsBySection200Response, Error<FetchTeamQuestionBankQuestionsBySectionError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_team_id = team_id;
    let p_path_section_id = section_id;
    let p_query_is_child = is_child;

    let uri_str = format!("{}/api/v1/teams/{teamId}/questions/section/{sectionId}", configuration.base_path, teamId=p_path_team_id, sectionId=p_path_section_id);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_is_child {
        req_builder = req_builder.query(&[("is_child", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::FetchTeamQuestionBankQuestionsBySection200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::FetchTeamQuestionBankQuestionsBySection200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<FetchTeamQuestionBankQuestionsBySectionError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Update a system question bank question - children and their versions are updated through parents
pub async fn update_question_bank_question(configuration: &configuration::Configuration, id: i32, update_question_bank_question_request: models::UpdateQuestionBankQuestionRequest) -> Result<models::UpdateQuestionBankQuestion200Response, Error<UpdateQuestionBankQuestionError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_id = id;
    let p_body_update_question_bank_question_request = update_question_bank_question_request;

    let uri_str = format!("{}/api/v1/questions/{id}", configuration.base_path, id=p_path_id);
    let mut req_builder = configuration.client.request(reqwest::Method::PUT, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&p_body_update_question_bank_question_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::UpdateQuestionBankQuestion200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::UpdateQuestionBankQuestion200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<UpdateQuestionBankQuestionError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Lock, unlock, archive or unarchive a question bank question
pub async fn update_question_bank_question_status(configuration: &configuration::Configuration, id: i32, status: &str) -> Result<models::UpdateQuestionBankQuestionStatus200Response, Error<UpdateQuestionBankQuestionStatusError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_id = id;
    let p_path_status = status;

    let uri_str = format!("{}/api/v1/questions/{id}/{status}", configuration.base_path, id=p_path_id, status=crate::apis::urlencode(p_path_status));
    let mut req_builder = configuration.client.request(reqwest::Method::PATCH, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::UpdateQuestionBankQuestionStatus200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::UpdateQuestionBankQuestionStatus200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<UpdateQuestionBankQuestionStatusError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

