/*
 * HDRUK Gateway API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};


/// struct for typed errors of method [`create_widget`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CreateWidgetError {
    Status400(models::CreateWidget400Response),
    Status500(models::CreateApplications500Response),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`delete_widget`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DeleteWidgetError {
    Status404(models::UpdateApplications404Response),
    Status500(models::CreateApplications500Response),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`fetch_all_widgets`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum FetchAllWidgetsError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`fetch_widget`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum FetchWidgetError {
    Status404(models::UpdateApplications404Response),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`fetch_widget_data_sources`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum FetchWidgetDataSourcesError {
    Status400(models::FetchWidgetDataSources400Response),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`retrieve_widget_data`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum RetrieveWidgetDataError {
    Status403(models::RetrieveWidgetData403Response),
    Status404(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`track_widget_event`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum TrackWidgetEventError {
    Status404(),
    Status422(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`update_widget`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum UpdateWidgetError {
    Status404(),
    Status500(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`widget_analytics`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum WidgetAnalyticsError {
    UnknownValue(serde_json::Value),
}


/// Creates a new widget for a given team
pub async fn create_widget(configuration: &configuration::Configuration, team_id: i32, create_widget_request: models::CreateWidgetRequest) -> Result<models::CreateWidget201Response, Error<CreateWidgetError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_team_id = team_id;
    let p_body_create_widget_request = create_widget_request;

    let uri_str = format!("{}/api/v1/teams/{teamId}/widgets", configuration.base_path, teamId=p_path_team_id);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&p_body_create_widget_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::CreateWidget201Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::CreateWidget201Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<CreateWidgetError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Soft delete a widget belonging to a specific team
pub async fn delete_widget(configuration: &configuration::Configuration, team_id: i32, id: i32) -> Result<models::DeleteApplications200Response, Error<DeleteWidgetError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_team_id = team_id;
    let p_path_id = id;

    let uri_str = format!("{}/api/v1/teams/{teamId}/widgets/{id}", configuration.base_path, teamId=p_path_team_id, id=p_path_id);
    let mut req_builder = configuration.client.request(reqwest::Method::DELETE, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::DeleteApplications200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::DeleteApplications200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<DeleteWidgetError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Get All Widgets
pub async fn fetch_all_widgets(configuration: &configuration::Configuration, team_id: i32) -> Result<models::FetchAllWidgets200Response, Error<FetchAllWidgetsError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_team_id = team_id;

    let uri_str = format!("{}/api/v1/teams/{teamId}/widgets", configuration.base_path, teamId=p_path_team_id);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::FetchAllWidgets200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::FetchAllWidgets200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<FetchAllWidgetsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Get a single Widget
pub async fn fetch_widget(configuration: &configuration::Configuration, team_id: i32, id: i32) -> Result<models::FetchWidget200Response, Error<FetchWidgetError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_team_id = team_id;
    let p_path_id = id;

    let uri_str = format!("{}/api/v1/teams/{teamId}/widgets/{id}", configuration.base_path, teamId=p_path_team_id, id=p_path_id);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::FetchWidget200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::FetchWidget200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<FetchWidgetError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Fetch lightweight data (id, name, etc.) for multiple teams across datasets, tools, collections, and DURS
pub async fn fetch_widget_data_sources(configuration: &configuration::Configuration, team_id: i32, team_ids: &str) -> Result<models::FetchWidgetDataSources200Response, Error<FetchWidgetDataSourcesError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_team_id = team_id;
    let p_query_team_ids = team_ids;

    let uri_str = format!("{}/api/v1/teams/{teamId}/widgets/data", configuration.base_path, teamId=p_path_team_id);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    req_builder = req_builder.query(&[("team_ids", &p_query_team_ids.to_string())]);
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::FetchWidgetDataSources200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::FetchWidgetDataSources200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<FetchWidgetDataSourcesError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Fetches datasets, data uses, scripts, and collections linked to a widget
pub async fn retrieve_widget_data(configuration: &configuration::Configuration, team_id: i32, id: i32, domain_origin: &str) -> Result<models::RetrieveWidgetData200Response, Error<RetrieveWidgetDataError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_team_id = team_id;
    let p_path_id = id;
    let p_query_domain_origin = domain_origin;

    let uri_str = format!("{}/api/v1/teams/{teamId}/widgets/{id}/data", configuration.base_path, teamId=p_path_team_id, id=p_path_id);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    req_builder = req_builder.query(&[("domain_origin", &p_query_domain_origin.to_string())]);
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::RetrieveWidgetData200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::RetrieveWidgetData200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<RetrieveWidgetDataError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Public endpoint for frontend clients to record user interactions with a widget (page views, code copies, gateway clicks, searches). No authentication required.
pub async fn track_widget_event(configuration: &configuration::Configuration, team_id: i32, id: i32, track_widget_event_request: models::TrackWidgetEventRequest) -> Result<(), Error<TrackWidgetEventError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_team_id = team_id;
    let p_path_id = id;
    let p_body_track_widget_event_request = track_widget_event_request;

    let uri_str = format!("{}/api/v1/teams/{teamId}/widgets/{id}/track", configuration.base_path, teamId=p_path_team_id, id=p_path_id);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.json(&p_body_track_widget_event_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<TrackWidgetEventError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Updates an existing widget for a given team ID
pub async fn update_widget(configuration: &configuration::Configuration, team_id: i32, id: i32, update_widget_request: Option<models::UpdateWidgetRequest>) -> Result<models::UpdateWidget200Response, Error<UpdateWidgetError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_team_id = team_id;
    let p_path_id = id;
    let p_body_update_widget_request = update_widget_request;

    let uri_str = format!("{}/api/v1/teams/{teamId}/widgets/{id}", configuration.base_path, teamId=p_path_team_id, id=p_path_id);
    let mut req_builder = configuration.client.request(reqwest::Method::PATCH, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&p_body_update_widget_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::UpdateWidget200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::UpdateWidget200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<UpdateWidgetError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Returns aggregated event counts per widget, per event type, and over time. Supports date range filtering and time-based grouping.
pub async fn widget_analytics(configuration: &configuration::Configuration, team_id: i32, from: Option<&str>, to: Option<&str>, group_by: Option<&str>) -> Result<models::WidgetAnalytics200Response, Error<WidgetAnalyticsError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_team_id = team_id;
    let p_query_from = from;
    let p_query_to = to;
    let p_query_group_by = group_by;

    let uri_str = format!("{}/api/v1/teams/{teamId}/widgets/analytics", configuration.base_path, teamId=p_path_team_id);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_from {
        req_builder = req_builder.query(&[("from", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_to {
        req_builder = req_builder.query(&[("to", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_group_by {
        req_builder = req_builder.query(&[("group_by", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::WidgetAnalytics200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::WidgetAnalytics200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<WidgetAnalyticsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

