/*
 * HDRUK Gateway API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateLibrariesRequest {
    #[serde(rename = "dataset_id")]
    pub dataset_id: i32,
}

impl CreateLibrariesRequest {
    pub fn new(dataset_id: i32) -> CreateLibrariesRequest {
        CreateLibrariesRequest {
            dataset_id,
        }
    }
}

