/*
 * HDRUK Gateway API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateQuestionBankQuestionRequestOptionsInnerChildrenInner {
    #[serde(rename = "force_required", skip_serializing_if = "Option::is_none")]
    pub force_required: Option<bool>,
    #[serde(rename = "allow_guidance_override", skip_serializing_if = "Option::is_none")]
    pub allow_guidance_override: Option<bool>,
    #[serde(rename = "locked", skip_serializing_if = "Option::is_none")]
    pub locked: Option<bool>,
    #[serde(rename = "archived", skip_serializing_if = "Option::is_none")]
    pub archived: Option<bool>,
    #[serde(rename = "component", skip_serializing_if = "Option::is_none")]
    pub component: Option<String>,
    #[serde(rename = "validations", skip_serializing_if = "Option::is_none")]
    pub validations: Option<Vec<serde_json::Value>>,
    #[serde(rename = "options", skip_serializing_if = "Option::is_none")]
    pub options: Option<Vec<models::CreateQuestionBankQuestionRequestOptionsInnerChildrenInnerOptionsInner>>,
    #[serde(rename = "title", skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    #[serde(rename = "guidance", skip_serializing_if = "Option::is_none")]
    pub guidance: Option<String>,
    #[serde(rename = "required", skip_serializing_if = "Option::is_none")]
    pub required: Option<bool>,
}

impl CreateQuestionBankQuestionRequestOptionsInnerChildrenInner {
    pub fn new() -> CreateQuestionBankQuestionRequestOptionsInnerChildrenInner {
        CreateQuestionBankQuestionRequestOptionsInnerChildrenInner {
            force_required: None,
            allow_guidance_override: None,
            locked: None,
            archived: None,
            component: None,
            validations: None,
            options: None,
            title: None,
            guidance: None,
            required: None,
        }
    }
}

