/*
 * HDRUK Gateway API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateEnquiryThreadsRequest {
    #[serde(rename = "user_id")]
    pub user_id: i32,
    #[serde(rename = "project_title")]
    pub project_title: String,
    #[serde(rename = "is_dar_dialogue", skip_serializing_if = "Option::is_none")]
    pub is_dar_dialogue: Option<bool>,
    #[serde(rename = "is_dar_status", skip_serializing_if = "Option::is_none")]
    pub is_dar_status: Option<bool>,
    #[serde(rename = "is_feasibility_enquiry", skip_serializing_if = "Option::is_none")]
    pub is_feasibility_enquiry: Option<bool>,
    #[serde(rename = "is_general_enquiry", skip_serializing_if = "Option::is_none")]
    pub is_general_enquiry: Option<bool>,
    #[serde(rename = "is_dar_review", skip_serializing_if = "Option::is_none")]
    pub is_dar_review: Option<bool>,
    #[serde(rename = "enabled", skip_serializing_if = "Option::is_none")]
    pub enabled: Option<bool>,
}

impl CreateEnquiryThreadsRequest {
    pub fn new(user_id: i32, project_title: String) -> CreateEnquiryThreadsRequest {
        CreateEnquiryThreadsRequest {
            user_id,
            project_title,
            is_dar_dialogue: None,
            is_dar_status: None,
            is_feasibility_enquiry: None,
            is_general_enquiry: None,
            is_dar_review: None,
            enabled: None,
        }
    }
}

