/*
 * HDRUK Gateway API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateDurRequestTeamInner {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "team_logo", skip_serializing_if = "Option::is_none")]
    pub team_logo: Option<String>,
    #[serde(rename = "member_of", skip_serializing_if = "Option::is_none")]
    pub member_of: Option<String>,
    #[serde(rename = "contact_point", skip_serializing_if = "Option::is_none")]
    pub contact_point: Option<String>,
}

impl CreateDurRequestTeamInner {
    pub fn new() -> CreateDurRequestTeamInner {
        CreateDurRequestTeamInner {
            id: None,
            name: None,
            team_logo: None,
            member_of: None,
            contact_point: None,
        }
    }
}

