/*
 * HDRUK Gateway API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateLicensesRequest {
    #[serde(rename = "code")]
    pub code: String,
    #[serde(rename = "label")]
    pub label: String,
    #[serde(rename = "valid_since")]
    pub valid_since: chrono::DateTime<chrono::FixedOffset>,
    #[serde(rename = "valid_until", skip_serializing_if = "Option::is_none")]
    pub valid_until: Option<chrono::DateTime<chrono::FixedOffset>>,
    #[serde(rename = "definition")]
    pub definition: String,
    #[serde(rename = "origin")]
    pub origin: String,
}

impl CreateLicensesRequest {
    pub fn new(code: String, label: String, valid_since: chrono::DateTime<chrono::FixedOffset>, definition: String, origin: String) -> CreateLicensesRequest {
        CreateLicensesRequest {
            code,
            label,
            valid_since,
            valid_until: None,
            definition,
            origin,
        }
    }
}

