/*
 * HDRUK Gateway API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DataAccessApplication : A Data Access Application (DAR) record managed by the Gateway
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DataAccessApplication {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    #[serde(rename = "applicant_id", skip_serializing_if = "Option::is_none")]
    pub applicant_id: Option<i32>,
    #[serde(rename = "project_title", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub project_title: Option<Option<String>>,
    #[serde(rename = "project_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub project_id: Option<Option<String>>,
    #[serde(rename = "application_type", skip_serializing_if = "Option::is_none")]
    pub application_type: Option<String>,
    #[serde(rename = "submission_status", skip_serializing_if = "Option::is_none")]
    pub submission_status: Option<SubmissionStatus>,
    #[serde(rename = "approval_status", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub approval_status: Option<Option<ApprovalStatus>>,
    #[serde(rename = "is_joint", skip_serializing_if = "Option::is_none")]
    pub is_joint: Option<bool>,
    #[serde(rename = "status_review_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub status_review_id: Option<Option<i32>>,
    #[serde(rename = "created_at", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<chrono::DateTime<chrono::FixedOffset>>,
    #[serde(rename = "updated_at", skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<chrono::DateTime<chrono::FixedOffset>>,
    #[serde(rename = "deleted_at", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub deleted_at: Option<Option<chrono::DateTime<chrono::FixedOffset>>>,
}

impl DataAccessApplication {
    /// A Data Access Application (DAR) record managed by the Gateway
    pub fn new() -> DataAccessApplication {
        DataAccessApplication {
            id: None,
            applicant_id: None,
            project_title: None,
            project_id: None,
            application_type: None,
            submission_status: None,
            approval_status: None,
            is_joint: None,
            status_review_id: None,
            created_at: None,
            updated_at: None,
            deleted_at: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum SubmissionStatus {
    #[serde(rename = "DRAFT")]
    Draft,
    #[serde(rename = "SUBMITTED")]
    Submitted,
    #[serde(rename = "FEEDBACK")]
    Feedback,
}

impl Default for SubmissionStatus {
    fn default() -> SubmissionStatus {
        Self::Draft
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ApprovalStatus {
    #[serde(rename = "APPROVED")]
    Approved,
    #[serde(rename = "APPROVED_COMMENTS")]
    ApprovedComments,
    #[serde(rename = "REJECTED")]
    Rejected,
    #[serde(rename = "WITHDRAWN")]
    Withdrawn,
}

impl Default for ApprovalStatus {
    fn default() -> ApprovalStatus {
        Self::Approved
    }
}

