/*
 * HDRUK Gateway API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Dur : A Data Use Register (DUR) entry describing an approved use of one or more datasets
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Dur {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    #[serde(rename = "project_title", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub project_title: Option<Option<String>>,
    #[serde(rename = "project_id_text", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub project_id_text: Option<Option<String>>,
    #[serde(rename = "organisation_name", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub organisation_name: Option<Option<String>>,
    #[serde(rename = "organisation_sector", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub organisation_sector: Option<Option<String>>,
    #[serde(rename = "sector_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub sector_id: Option<Option<i32>>,
    #[serde(rename = "lay_summary", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub lay_summary: Option<Option<String>>,
    #[serde(rename = "technical_summary", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub technical_summary: Option<Option<String>>,
    #[serde(rename = "latest_approval_date", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub latest_approval_date: Option<Option<chrono::NaiveDate>>,
    #[serde(rename = "manual_upload", skip_serializing_if = "Option::is_none")]
    pub manual_upload: Option<bool>,
    #[serde(rename = "rejection_reason", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub rejection_reason: Option<Option<String>>,
    #[serde(rename = "sublicence_arrangements", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub sublicence_arrangements: Option<Option<String>>,
    #[serde(rename = "public_benefit_statement", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub public_benefit_statement: Option<Option<String>>,
    #[serde(rename = "data_sensitivity_level", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub data_sensitivity_level: Option<Option<String>>,
    #[serde(rename = "project_start_date", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub project_start_date: Option<Option<chrono::NaiveDate>>,
    #[serde(rename = "project_end_date", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub project_end_date: Option<Option<chrono::NaiveDate>>,
    #[serde(rename = "access_date", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub access_date: Option<Option<chrono::NaiveDate>>,
    #[serde(rename = "accredited_researcher_status", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub accredited_researcher_status: Option<Option<String>>,
    #[serde(rename = "confidential_data_description", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub confidential_data_description: Option<Option<String>>,
    #[serde(rename = "dataset_linkage_description", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub dataset_linkage_description: Option<Option<String>>,
    #[serde(rename = "duty_of_confidentiality", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub duty_of_confidentiality: Option<Option<String>>,
    #[serde(rename = "legal_basis_for_data_article6", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub legal_basis_for_data_article6: Option<Option<String>>,
    #[serde(rename = "legal_basis_for_data_article9", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub legal_basis_for_data_article9: Option<Option<String>>,
    #[serde(rename = "national_data_optout", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub national_data_optout: Option<Option<String>>,
    #[serde(rename = "organisation_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub organisation_id: Option<Option<String>>,
    #[serde(rename = "privacy_enhancements", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub privacy_enhancements: Option<Option<String>>,
    #[serde(rename = "request_category_type", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub request_category_type: Option<Option<String>>,
    #[serde(rename = "request_frequency", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub request_frequency: Option<Option<String>>,
    #[serde(rename = "access_type", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub access_type: Option<Option<String>>,
    #[serde(rename = "non_gateway_datasets", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub non_gateway_datasets: Option<Option<Vec<String>>>,
    #[serde(rename = "non_gateway_applicants", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub non_gateway_applicants: Option<Option<Vec<String>>>,
    #[serde(rename = "funders_and_sponsors", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub funders_and_sponsors: Option<Option<Vec<String>>>,
    #[serde(rename = "other_approval_committees", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub other_approval_committees: Option<Option<Vec<String>>>,
    #[serde(rename = "gateway_outputs_tools", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub gateway_outputs_tools: Option<Option<Vec<String>>>,
    #[serde(rename = "gateway_outputs_papers", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub gateway_outputs_papers: Option<Option<Vec<String>>>,
    #[serde(rename = "non_gateway_outputs", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub non_gateway_outputs: Option<Option<Vec<String>>>,
    #[serde(rename = "enabled", skip_serializing_if = "Option::is_none")]
    pub enabled: Option<bool>,
    #[serde(rename = "last_activity", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub last_activity: Option<Option<chrono::DateTime<chrono::FixedOffset>>>,
    #[serde(rename = "counter", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub counter: Option<Option<i32>>,
    #[serde(rename = "user_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub user_id: Option<Option<i32>>,
    #[serde(rename = "team_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub team_id: Option<Option<i32>>,
    #[serde(rename = "applicant_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub applicant_id: Option<Option<i32>>,
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<Status>,
    #[serde(rename = "created_at", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<chrono::DateTime<chrono::FixedOffset>>,
    #[serde(rename = "updated_at", skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<chrono::DateTime<chrono::FixedOffset>>,
}

impl Dur {
    /// A Data Use Register (DUR) entry describing an approved use of one or more datasets
    pub fn new() -> Dur {
        Dur {
            id: None,
            project_title: None,
            project_id_text: None,
            organisation_name: None,
            organisation_sector: None,
            sector_id: None,
            lay_summary: None,
            technical_summary: None,
            latest_approval_date: None,
            manual_upload: None,
            rejection_reason: None,
            sublicence_arrangements: None,
            public_benefit_statement: None,
            data_sensitivity_level: None,
            project_start_date: None,
            project_end_date: None,
            access_date: None,
            accredited_researcher_status: None,
            confidential_data_description: None,
            dataset_linkage_description: None,
            duty_of_confidentiality: None,
            legal_basis_for_data_article6: None,
            legal_basis_for_data_article9: None,
            national_data_optout: None,
            organisation_id: None,
            privacy_enhancements: None,
            request_category_type: None,
            request_frequency: None,
            access_type: None,
            non_gateway_datasets: None,
            non_gateway_applicants: None,
            funders_and_sponsors: None,
            other_approval_committees: None,
            gateway_outputs_tools: None,
            gateway_outputs_papers: None,
            non_gateway_outputs: None,
            enabled: None,
            last_activity: None,
            counter: None,
            user_id: None,
            team_id: None,
            applicant_id: None,
            status: None,
            created_at: None,
            updated_at: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "ACTIVE")]
    Active,
    #[serde(rename = "DRAFT")]
    Draft,
    #[serde(rename = "ARCHIVED")]
    Archived,
}

impl Default for Status {
    fn default() -> Status {
        Self::Active
    }
}

