/*
 * HDRUK Gateway API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EditQuestionBankQuestionRequest {
    #[serde(rename = "section_id", skip_serializing_if = "Option::is_none")]
    pub section_id: Option<i32>,
    #[serde(rename = "user_id", skip_serializing_if = "Option::is_none")]
    pub user_id: Option<i32>,
    #[serde(rename = "team_ids", skip_serializing_if = "Option::is_none")]
    pub team_ids: Option<Vec<i32>>,
    #[serde(rename = "locked", skip_serializing_if = "Option::is_none")]
    pub locked: Option<bool>,
    #[serde(rename = "archived", skip_serializing_if = "Option::is_none")]
    pub archived: Option<bool>,
    #[serde(rename = "force_required", skip_serializing_if = "Option::is_none")]
    pub force_required: Option<bool>,
    #[serde(rename = "allow_guidance_override", skip_serializing_if = "Option::is_none")]
    pub allow_guidance_override: Option<bool>,
    #[serde(rename = "question_type", skip_serializing_if = "Option::is_none")]
    pub question_type: Option<String>,
    #[serde(rename = "default", skip_serializing_if = "Option::is_none")]
    pub default: Option<bool>,
    #[serde(rename = "guidance", skip_serializing_if = "Option::is_none")]
    pub guidance: Option<String>,
    #[serde(rename = "title", skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    #[serde(rename = "field", skip_serializing_if = "Option::is_none")]
    pub field: Option<Vec<serde_json::Value>>,
}

impl EditQuestionBankQuestionRequest {
    pub fn new() -> EditQuestionBankQuestionRequest {
        EditQuestionBankQuestionRequest {
            section_id: None,
            user_id: None,
            team_ids: None,
            locked: None,
            archived: None,
            force_required: None,
            allow_guidance_override: None,
            question_type: None,
            default: None,
            guidance: None,
            title: None,
            field: None,
        }
    }
}

