/*
 * HDRUK Gateway API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FetchStandardQuestionBankQuestions200Response {
    #[serde(rename = "current_page", skip_serializing_if = "Option::is_none")]
    pub current_page: Option<i32>,
    #[serde(rename = "data", skip_serializing_if = "Option::is_none")]
    pub data: Option<Box<Vec<serde_json::Value>>>,
}

impl FetchStandardQuestionBankQuestions200Response {
    pub fn new() -> FetchStandardQuestionBankQuestions200Response {
        FetchStandardQuestionBankQuestions200Response {
            current_page: None,
            data: None,
        }
    }
}

