/*
 * HDRUK Gateway API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FetchDataProviderCollSummary200ResponseData {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "img_url", skip_serializing_if = "Option::is_none")]
    pub img_url: Option<String>,
    #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
    #[serde(rename = "summary", skip_serializing_if = "Option::is_none")]
    pub summary: Option<String>,
    #[serde(rename = "datasets", skip_serializing_if = "Option::is_none")]
    pub datasets: Option<Vec<serde_json::Value>>,
    #[serde(rename = "durs", skip_serializing_if = "Option::is_none")]
    pub durs: Option<Vec<serde_json::Value>>,
    #[serde(rename = "tools", skip_serializing_if = "Option::is_none")]
    pub tools: Option<Vec<serde_json::Value>>,
    #[serde(rename = "publications", skip_serializing_if = "Option::is_none")]
    pub publications: Option<Vec<serde_json::Value>>,
    #[serde(rename = "collections", skip_serializing_if = "Option::is_none")]
    pub collections: Option<Vec<serde_json::Value>>,
    #[serde(rename = "service", skip_serializing_if = "Option::is_none")]
    pub service: Option<String>,
}

impl FetchDataProviderCollSummary200ResponseData {
    pub fn new() -> FetchDataProviderCollSummary200ResponseData {
        FetchDataProviderCollSummary200ResponseData {
            id: None,
            name: None,
            img_url: None,
            url: None,
            summary: None,
            datasets: None,
            durs: None,
            tools: None,
            publications: None,
            collections: None,
            service: None,
        }
    }
}

