/*
 * HDRUK Gateway API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FetchDataCustodianNetworkEntitiesSummary200ResponseData {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    #[serde(rename = "durs_total", skip_serializing_if = "Option::is_none")]
    pub durs_total: Option<i32>,
    #[serde(rename = "durs", skip_serializing_if = "Option::is_none")]
    pub durs: Option<Vec<serde_json::Value>>,
    #[serde(rename = "tools_total", skip_serializing_if = "Option::is_none")]
    pub tools_total: Option<i32>,
    #[serde(rename = "tools", skip_serializing_if = "Option::is_none")]
    pub tools: Option<Vec<serde_json::Value>>,
    #[serde(rename = "publications_total", skip_serializing_if = "Option::is_none")]
    pub publications_total: Option<i32>,
    #[serde(rename = "publications", skip_serializing_if = "Option::is_none")]
    pub publications: Option<Vec<serde_json::Value>>,
    #[serde(rename = "collections_total", skip_serializing_if = "Option::is_none")]
    pub collections_total: Option<i32>,
    #[serde(rename = "collections", skip_serializing_if = "Option::is_none")]
    pub collections: Option<Vec<serde_json::Value>>,
}

impl FetchDataCustodianNetworkEntitiesSummary200ResponseData {
    pub fn new() -> FetchDataCustodianNetworkEntitiesSummary200ResponseData {
        FetchDataCustodianNetworkEntitiesSummary200ResponseData {
            id: None,
            durs_total: None,
            durs: None,
            tools_total: None,
            tools: None,
            publications_total: None,
            publications: None,
            collections_total: None,
            collections: None,
        }
    }
}

