/*
 * HDRUK Gateway API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FetchTeamDarApplicationHeader200ResponseDataTeamsInner {
    #[serde(rename = "team_id", skip_serializing_if = "Option::is_none")]
    pub team_id: Option<i32>,
    #[serde(rename = "dar_application_id", skip_serializing_if = "Option::is_none")]
    pub dar_application_id: Option<i32>,
    #[serde(rename = "submission_status", skip_serializing_if = "Option::is_none")]
    pub submission_status: Option<String>,
    #[serde(rename = "approval_status", skip_serializing_if = "Option::is_none")]
    pub approval_status: Option<String>,
}

impl FetchTeamDarApplicationHeader200ResponseDataTeamsInner {
    pub fn new() -> FetchTeamDarApplicationHeader200ResponseDataTeamsInner {
        FetchTeamDarApplicationHeader200ResponseDataTeamsInner {
            team_id: None,
            dar_application_id: None,
            submission_status: None,
            approval_status: None,
        }
    }
}

