/*
 * HDRUK Gateway API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FetchTeamDarApplicationAnswers200ResponseData {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    #[serde(rename = "answers", skip_serializing_if = "Option::is_none")]
    pub answers: Option<Vec<serde_json::Value>>,
}

impl FetchTeamDarApplicationAnswers200ResponseData {
    pub fn new() -> FetchTeamDarApplicationAnswers200ResponseData {
        FetchTeamDarApplicationAnswers200ResponseData {
            id: None,
            answers: None,
        }
    }
}

