/*
 * HDRUK Gateway API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FetchTeamDarApplicationHeader200ResponseData {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    #[serde(rename = "created_at", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<chrono::DateTime<chrono::FixedOffset>>,
    #[serde(rename = "updated_at", skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<chrono::DateTime<chrono::FixedOffset>>,
    #[serde(rename = "deleted_at", skip_serializing_if = "Option::is_none")]
    pub deleted_at: Option<chrono::DateTime<chrono::FixedOffset>>,
    #[serde(rename = "applicant_id", skip_serializing_if = "Option::is_none")]
    pub applicant_id: Option<i32>,
    #[serde(rename = "project_title", skip_serializing_if = "Option::is_none")]
    pub project_title: Option<String>,
    #[serde(rename = "application_type", skip_serializing_if = "Option::is_none")]
    pub application_type: Option<String>,
    #[serde(rename = "project_id", skip_serializing_if = "Option::is_none")]
    pub project_id: Option<i32>,
    #[serde(rename = "is_joint", skip_serializing_if = "Option::is_none")]
    pub is_joint: Option<bool>,
    #[serde(rename = "approval_status", skip_serializing_if = "Option::is_none")]
    pub approval_status: Option<String>,
    #[serde(rename = "submission_status", skip_serializing_if = "Option::is_none")]
    pub submission_status: Option<String>,
    #[serde(rename = "status_review_id", skip_serializing_if = "Option::is_none")]
    pub status_review_id: Option<i32>,
    #[serde(rename = "days_since_submission", skip_serializing_if = "Option::is_none")]
    pub days_since_submission: Option<i32>,
    #[serde(rename = "primary_applicant", skip_serializing_if = "Option::is_none")]
    pub primary_applicant: Option<Vec<models::FetchTeamDarApplicationHeader200ResponseDataPrimaryApplicantInner>>,
    #[serde(rename = "datasets", skip_serializing_if = "Option::is_none")]
    pub datasets: Option<Vec<models::FetchTeamDarApplicationHeader200ResponseDataDatasetsInner>>,
    #[serde(rename = "teams", skip_serializing_if = "Option::is_none")]
    pub teams: Option<Vec<models::FetchTeamDarApplicationHeader200ResponseDataTeamsInner>>,
}

impl FetchTeamDarApplicationHeader200ResponseData {
    pub fn new() -> FetchTeamDarApplicationHeader200ResponseData {
        FetchTeamDarApplicationHeader200ResponseData {
            id: None,
            created_at: None,
            updated_at: None,
            deleted_at: None,
            applicant_id: None,
            project_title: None,
            application_type: None,
            project_id: None,
            is_joint: None,
            approval_status: None,
            submission_status: None,
            status_review_id: None,
            days_since_submission: None,
            primary_applicant: None,
            datasets: None,
            teams: None,
        }
    }
}

