/*
 * HDRUK Gateway API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetFederationHistory200ResponseDataInner {
    #[serde(rename = "job_uuid", skip_serializing_if = "Option::is_none")]
    pub job_uuid: Option<String>,
    #[serde(rename = "started_at", skip_serializing_if = "Option::is_none")]
    pub started_at: Option<chrono::DateTime<chrono::FixedOffset>>,
    #[serde(rename = "finished_at", skip_serializing_if = "Option::is_none")]
    pub finished_at: Option<chrono::DateTime<chrono::FixedOffset>>,
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<Status>,
    #[serde(rename = "message", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub message: Option<Option<String>>,
    #[serde(rename = "failed_datasets", skip_serializing_if = "Option::is_none")]
    pub failed_datasets: Option<Vec<models::GetFederationHistory200ResponseDataInnerFailedDatasetsInner>>,
}

impl GetFederationHistory200ResponseDataInner {
    pub fn new() -> GetFederationHistory200ResponseDataInner {
        GetFederationHistory200ResponseDataInner {
            job_uuid: None,
            started_at: None,
            finished_at: None,
            status: None,
            message: None,
            failed_datasets: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "success")]
    Success,
    #[serde(rename = "failed")]
    Failed,
    #[serde(rename = "in_progress")]
    InProgress,
}

impl Default for Status {
    fn default() -> Status {
        Self::Success
    }
}

