/*
 * HDRUK Gateway API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GetFederationTeamId200ResponseDataInnerProgress : Only present while a sync is actively in progress
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetFederationTeamId200ResponseDataInnerProgress {
    #[serde(rename = "total", skip_serializing_if = "Option::is_none")]
    pub total: Option<i32>,
    #[serde(rename = "processed", skip_serializing_if = "Option::is_none")]
    pub processed: Option<i32>,
    #[serde(rename = "failed", skip_serializing_if = "Option::is_none")]
    pub failed: Option<i32>,
    #[serde(rename = "pending", skip_serializing_if = "Option::is_none")]
    pub pending: Option<i32>,
    #[serde(rename = "started_at", skip_serializing_if = "Option::is_none")]
    pub started_at: Option<chrono::DateTime<chrono::FixedOffset>>,
}

impl GetFederationTeamId200ResponseDataInnerProgress {
    /// Only present while a sync is actively in progress
    pub fn new() -> GetFederationTeamId200ResponseDataInnerProgress {
        GetFederationTeamId200ResponseDataInnerProgress {
            total: None,
            processed: None,
            failed: None,
            pending: None,
            started_at: None,
        }
    }
}

