/*
 * HDRUK Gateway API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetCancerTypeFilter200Response {
    #[serde(rename = "data", skip_serializing_if = "Option::is_none")]
    pub data: Option<Box<models::GetCancerTypeFilters200ResponseDataInner>>,
}

impl GetCancerTypeFilter200Response {
    pub fn new() -> GetCancerTypeFilter200Response {
        GetCancerTypeFilter200Response {
            data: None,
        }
    }
}

