/*
 * HDRUK Gateway API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetFederationHistory200Response {
    #[serde(rename = "current_page", skip_serializing_if = "Option::is_none")]
    pub current_page: Option<i32>,
    #[serde(rename = "data", skip_serializing_if = "Option::is_none")]
    pub data: Option<Vec<models::GetFederationHistory200ResponseDataInner>>,
    #[serde(rename = "first_page_url", skip_serializing_if = "Option::is_none")]
    pub first_page_url: Option<String>,
    #[serde(rename = "from", skip_serializing_if = "Option::is_none")]
    pub from: Option<i32>,
    #[serde(rename = "last_page", skip_serializing_if = "Option::is_none")]
    pub last_page: Option<i32>,
    #[serde(rename = "last_page_url", skip_serializing_if = "Option::is_none")]
    pub last_page_url: Option<String>,
    #[serde(rename = "links", skip_serializing_if = "Option::is_none")]
    pub links: Option<Vec<Vec<serde_json::Value>>>,
    #[serde(rename = "next_page_url", skip_serializing_if = "Option::is_none")]
    pub next_page_url: Option<String>,
    #[serde(rename = "path", skip_serializing_if = "Option::is_none")]
    pub path: Option<String>,
    #[serde(rename = "per_page", skip_serializing_if = "Option::is_none")]
    pub per_page: Option<i32>,
    #[serde(rename = "prev_page_url", skip_serializing_if = "Option::is_none")]
    pub prev_page_url: Option<String>,
    #[serde(rename = "to", skip_serializing_if = "Option::is_none")]
    pub to: Option<i32>,
    #[serde(rename = "total", skip_serializing_if = "Option::is_none")]
    pub total: Option<i32>,
}

impl GetFederationHistory200Response {
    pub fn new() -> GetFederationHistory200Response {
        GetFederationHistory200Response {
            current_page: None,
            data: None,
            first_page_url: None,
            from: None,
            last_page: None,
            last_page_url: None,
            links: None,
            next_page_url: None,
            path: None,
            per_page: None,
            prev_page_url: None,
            to: None,
            total: None,
        }
    }
}

