/*
 * HDRUK Gateway API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListLibraries200ResponseDataInner {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    #[serde(rename = "created_at", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<chrono::DateTime<chrono::FixedOffset>>,
    #[serde(rename = "updated_at", skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<chrono::DateTime<chrono::FixedOffset>>,
    #[serde(rename = "user_id", skip_serializing_if = "Option::is_none")]
    pub user_id: Option<i32>,
    #[serde(rename = "dataset_id", skip_serializing_if = "Option::is_none")]
    pub dataset_id: Option<String>,
    #[serde(rename = "dataset_status", skip_serializing_if = "Option::is_none")]
    pub dataset_status: Option<String>,
    #[serde(rename = "data_provider_id", skip_serializing_if = "Option::is_none")]
    pub data_provider_id: Option<String>,
    #[serde(rename = "data_provider_dar_status", skip_serializing_if = "Option::is_none")]
    pub data_provider_dar_status: Option<bool>,
    #[serde(rename = "data_provider_name", skip_serializing_if = "Option::is_none")]
    pub data_provider_name: Option<String>,
}

impl ListLibraries200ResponseDataInner {
    pub fn new() -> ListLibraries200ResponseDataInner {
        ListLibraries200ResponseDataInner {
            id: None,
            created_at: None,
            updated_at: None,
            user_id: None,
            dataset_id: None,
            dataset_status: None,
            data_provider_id: None,
            data_provider_dar_status: None,
            data_provider_name: None,
        }
    }
}

