/*
 * HDRUK Gateway API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// QuestionBank : A question bank question record managed by the Gateway
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct QuestionBank {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    #[serde(rename = "section_id", skip_serializing_if = "Option::is_none")]
    pub section_id: Option<i32>,
    #[serde(rename = "user_id", skip_serializing_if = "Option::is_none")]
    pub user_id: Option<i32>,
    #[serde(rename = "locked", skip_serializing_if = "Option::is_none")]
    pub locked: Option<bool>,
    #[serde(rename = "archived", skip_serializing_if = "Option::is_none")]
    pub archived: Option<bool>,
    #[serde(rename = "archived_date", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub archived_date: Option<Option<chrono::DateTime<chrono::FixedOffset>>>,
    #[serde(rename = "force_required", skip_serializing_if = "Option::is_none")]
    pub force_required: Option<bool>,
    #[serde(rename = "allow_guidance_override", skip_serializing_if = "Option::is_none")]
    pub allow_guidance_override: Option<bool>,
    #[serde(rename = "is_child", skip_serializing_if = "Option::is_none")]
    pub is_child: Option<bool>,
    #[serde(rename = "question_type", skip_serializing_if = "Option::is_none")]
    pub question_type: Option<QuestionType>,
    #[serde(rename = "created_at", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<chrono::DateTime<chrono::FixedOffset>>,
    #[serde(rename = "updated_at", skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<chrono::DateTime<chrono::FixedOffset>>,
}

impl QuestionBank {
    /// A question bank question record managed by the Gateway
    pub fn new() -> QuestionBank {
        QuestionBank {
            id: None,
            section_id: None,
            user_id: None,
            locked: None,
            archived: None,
            archived_date: None,
            force_required: None,
            allow_guidance_override: None,
            is_child: None,
            question_type: None,
            created_at: None,
            updated_at: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum QuestionType {
    #[serde(rename = "STANDARD")]
    Standard,
    #[serde(rename = "CUSTOM")]
    Custom,
}

impl Default for QuestionType {
    fn default() -> QuestionType {
        Self::Standard
    }
}

