/*
 * HDRUK Gateway API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SearchTools200ResponseDataInner {
    #[serde(rename = "_source", skip_serializing_if = "Option::is_none")]
    pub _source: Option<Vec<models::SearchTools200ResponseDataInnerSourceInner>>,
    #[serde(rename = "highlight", skip_serializing_if = "Option::is_none")]
    pub highlight: Option<Vec<models::SearchTools200ResponseDataInnerHighlightInner>>,
    #[serde(rename = "uploader", skip_serializing_if = "Option::is_none")]
    pub uploader: Option<String>,
    #[serde(rename = "team_name", skip_serializing_if = "Option::is_none")]
    pub team_name: Option<String>,
    #[serde(rename = "type_category", skip_serializing_if = "Option::is_none")]
    pub type_category: Option<Vec<serde_json::Value>>,
    #[serde(rename = "license", skip_serializing_if = "Option::is_none")]
    pub license: Option<String>,
    #[serde(rename = "programming_language", skip_serializing_if = "Option::is_none")]
    pub programming_language: Option<Vec<serde_json::Value>>,
    #[serde(rename = "programming_package", skip_serializing_if = "Option::is_none")]
    pub programming_package: Option<Vec<serde_json::Value>>,
    #[serde(rename = "datasets", skip_serializing_if = "Option::is_none")]
    pub datasets: Option<Vec<serde_json::Value>>,
}

impl SearchTools200ResponseDataInner {
    pub fn new() -> SearchTools200ResponseDataInner {
        SearchTools200ResponseDataInner {
            _source: None,
            highlight: None,
            uploader: None,
            team_name: None,
            type_category: None,
            license: None,
            programming_language: None,
            programming_package: None,
            datasets: None,
        }
    }
}

