/*
 * HDRUK Gateway API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SearchDataCustodians200ResponseDataInner {
    #[serde(rename = "_source", skip_serializing_if = "Option::is_none")]
    pub _source: Option<Vec<models::SearchDataCustodians200ResponseDataInnerSourceInner>>,
    #[serde(rename = "highlight", skip_serializing_if = "Option::is_none")]
    pub highlight: Option<Vec<models::SearchDataUses200ResponseDataInnerHighlightInner>>,
}

impl SearchDataCustodians200ResponseDataInner {
    pub fn new() -> SearchDataCustodians200ResponseDataInner {
        SearchDataCustodians200ResponseDataInner {
            _source: None,
            highlight: None,
        }
    }
}

