/*
 * HDRUK Gateway API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SearchDataCustodianNetworks200ResponseDataInnerSourceInner {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "img_url", skip_serializing_if = "Option::is_none")]
    pub img_url: Option<String>,
    #[serde(rename = "datasetTitles", skip_serializing_if = "Option::is_none")]
    pub dataset_titles: Option<Vec<serde_json::Value>>,
    #[serde(rename = "geographicLocation", skip_serializing_if = "Option::is_none")]
    pub geographic_location: Option<Vec<serde_json::Value>>,
}

impl SearchDataCustodianNetworks200ResponseDataInnerSourceInner {
    pub fn new() -> SearchDataCustodianNetworks200ResponseDataInnerSourceInner {
        SearchDataCustodianNetworks200ResponseDataInnerSourceInner {
            id: None,
            name: None,
            img_url: None,
            dataset_titles: None,
            geographic_location: None,
        }
    }
}

