/*
 * HDRUK Gateway API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Team : A data custodian team that owns datasets and manages data access
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Team {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "enabled", skip_serializing_if = "Option::is_none")]
    pub enabled: Option<bool>,
    #[serde(rename = "allows_messaging", skip_serializing_if = "Option::is_none")]
    pub allows_messaging: Option<bool>,
    #[serde(rename = "workflow_enabled", skip_serializing_if = "Option::is_none")]
    pub workflow_enabled: Option<bool>,
    #[serde(rename = "access_requests_management", skip_serializing_if = "Option::is_none")]
    pub access_requests_management: Option<bool>,
    #[serde(rename = "uses_5_safes", skip_serializing_if = "Option::is_none")]
    pub uses_5_safes: Option<bool>,
    #[serde(rename = "is_admin", skip_serializing_if = "Option::is_none")]
    pub is_admin: Option<bool>,
    #[serde(rename = "member_of", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub member_of: Option<Option<String>>,
    #[serde(rename = "contact_point", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub contact_point: Option<Option<String>>,
    #[serde(rename = "notification_status", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub notification_status: Option<Option<bool>>,
    #[serde(rename = "is_question_bank", skip_serializing_if = "Option::is_none")]
    pub is_question_bank: Option<bool>,
    #[serde(rename = "team_logo", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub team_logo: Option<Option<String>>,
    #[serde(rename = "introduction", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub introduction: Option<Option<String>>,
    #[serde(rename = "dar_modal_content", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub dar_modal_content: Option<Option<String>>,
    #[serde(rename = "dar_modal_header", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub dar_modal_header: Option<Option<String>>,
    #[serde(rename = "dar_modal_footer", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub dar_modal_footer: Option<Option<String>>,
    #[serde(rename = "service", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub service: Option<Option<String>>,
    #[serde(rename = "is_dar", skip_serializing_if = "Option::is_none")]
    pub is_dar: Option<bool>,
    /// Public identifier, cast to string
    #[serde(rename = "pid", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub pid: Option<Option<String>>,
    #[serde(rename = "created_at", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<chrono::DateTime<chrono::FixedOffset>>,
    #[serde(rename = "updated_at", skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<chrono::DateTime<chrono::FixedOffset>>,
}

impl Team {
    /// A data custodian team that owns datasets and manages data access
    pub fn new() -> Team {
        Team {
            id: None,
            name: None,
            enabled: None,
            allows_messaging: None,
            workflow_enabled: None,
            access_requests_management: None,
            uses_5_safes: None,
            is_admin: None,
            member_of: None,
            contact_point: None,
            notification_status: None,
            is_question_bank: None,
            team_logo: None,
            introduction: None,
            dar_modal_content: None,
            dar_modal_header: None,
            dar_modal_footer: None,
            service: None,
            is_dar: None,
            pid: None,
            created_at: None,
            updated_at: None,
        }
    }
}

