/*
 * HDRUK Gateway API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TrackWidgetEventRequest {
    #[serde(rename = "event_type")]
    pub event_type: EventType,
    #[serde(rename = "entity_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub entity_id: Option<Option<i32>>,
    #[serde(rename = "entity_type", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub entity_type: Option<Option<EntityType>>,
    #[serde(rename = "source_domain", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub source_domain: Option<Option<String>>,
}

impl TrackWidgetEventRequest {
    pub fn new(event_type: EventType) -> TrackWidgetEventRequest {
        TrackWidgetEventRequest {
            event_type,
            entity_id: None,
            entity_type: None,
            source_domain: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum EventType {
    #[serde(rename = "page_view")]
    PageView,
    #[serde(rename = "code_copied")]
    CodeCopied,
    #[serde(rename = "gateway_click")]
    GatewayClick,
    #[serde(rename = "search")]
    Search,
}

impl Default for EventType {
    fn default() -> EventType {
        Self::PageView
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum EntityType {
    #[serde(rename = "dataset")]
    Dataset,
    #[serde(rename = "tool")]
    Tool,
    #[serde(rename = "collection")]
    Collection,
    #[serde(rename = "dur")]
    Dur,
}

impl Default for EntityType {
    fn default() -> EntityType {
        Self::Dataset
    }
}

