/*
 * HDRUK Gateway API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateTeamDarApplicationRequest {
    #[serde(rename = "submission_status", skip_serializing_if = "Option::is_none")]
    pub submission_status: Option<String>,
    #[serde(rename = "approval_status", skip_serializing_if = "Option::is_none")]
    pub approval_status: Option<String>,
    #[serde(rename = "comment", skip_serializing_if = "Option::is_none")]
    pub comment: Option<String>,
}

impl UpdateTeamDarApplicationRequest {
    pub fn new() -> UpdateTeamDarApplicationRequest {
        UpdateTeamDarApplicationRequest {
            submission_status: None,
            approval_status: None,
            comment: None,
        }
    }
}

