/*
 * HDRUK Gateway API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateUserDarApplicationRequest {
    #[serde(rename = "applicant_id")]
    pub applicant_id: i32,
    #[serde(rename = "submission_status")]
    pub submission_status: String,
    #[serde(rename = "project_title", skip_serializing_if = "Option::is_none")]
    pub project_title: Option<String>,
    #[serde(rename = "approval_status")]
    pub approval_status: String,
    #[serde(rename = "team_ids", skip_serializing_if = "Option::is_none")]
    pub team_ids: Option<Vec<i32>>,
    #[serde(rename = "answers", skip_serializing_if = "Option::is_none")]
    pub answers: Option<Vec<models::UpdateUserDarApplicationRequestAnswersInner>>,
}

impl UpdateUserDarApplicationRequest {
    pub fn new(applicant_id: i32, submission_status: String, approval_status: String) -> UpdateUserDarApplicationRequest {
        UpdateUserDarApplicationRequest {
            applicant_id,
            submission_status,
            project_title: None,
            approval_status,
            team_ids: None,
            answers: None,
        }
    }
}

