/*
 * HDRUK Gateway API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateWidgetRequest {
    #[serde(rename = "widget_name", skip_serializing_if = "Option::is_none")]
    pub widget_name: Option<String>,
    #[serde(rename = "size_width", skip_serializing_if = "Option::is_none")]
    pub size_width: Option<i32>,
    #[serde(rename = "size_height", skip_serializing_if = "Option::is_none")]
    pub size_height: Option<i32>,
    #[serde(rename = "unit", skip_serializing_if = "Option::is_none")]
    pub unit: Option<Unit>,
    #[serde(rename = "include_search_bar", skip_serializing_if = "Option::is_none")]
    pub include_search_bar: Option<bool>,
    #[serde(rename = "include_cohort_link", skip_serializing_if = "Option::is_none")]
    pub include_cohort_link: Option<bool>,
    #[serde(rename = "keep_proportions", skip_serializing_if = "Option::is_none")]
    pub keep_proportions: Option<bool>,
    #[serde(rename = "permitted_domains", skip_serializing_if = "Option::is_none")]
    pub permitted_domains: Option<Vec<String>>,
    #[serde(rename = "included_datasets", skip_serializing_if = "Option::is_none")]
    pub included_datasets: Option<Vec<i32>>,
    #[serde(rename = "included_data_uses", skip_serializing_if = "Option::is_none")]
    pub included_data_uses: Option<Vec<i32>>,
    #[serde(rename = "data_custodian_entities_ids", skip_serializing_if = "Option::is_none")]
    pub data_custodian_entities_ids: Option<Vec<i32>>,
    #[serde(rename = "included_scripts", skip_serializing_if = "Option::is_none")]
    pub included_scripts: Option<Vec<i32>>,
    #[serde(rename = "included_collections", skip_serializing_if = "Option::is_none")]
    pub included_collections: Option<Vec<i32>>,
}

impl UpdateWidgetRequest {
    pub fn new() -> UpdateWidgetRequest {
        UpdateWidgetRequest {
            widget_name: None,
            size_width: None,
            size_height: None,
            unit: None,
            include_search_bar: None,
            include_cohort_link: None,
            keep_proportions: None,
            permitted_domains: None,
            included_datasets: None,
            included_data_uses: None,
            data_custodian_entities_ids: None,
            included_scripts: None,
            included_collections: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Unit {
    #[serde(rename = "px")]
    Px,
    #[serde(rename = "%")]
    Percent,
    #[serde(rename = "rem")]
    Rem,
}

impl Default for Unit {
    fn default() -> Unit {
        Self::Px
    }
}

