/*
 * HDRUK Gateway API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateQuestionBankQuestionRequest {
    #[serde(rename = "section_id")]
    pub section_id: i32,
    #[serde(rename = "user_id", skip_serializing_if = "Option::is_none")]
    pub user_id: Option<i32>,
    #[serde(rename = "team_ids", skip_serializing_if = "Option::is_none")]
    pub team_ids: Option<Vec<i32>>,
    #[serde(rename = "locked", skip_serializing_if = "Option::is_none")]
    pub locked: Option<bool>,
    #[serde(rename = "archived", skip_serializing_if = "Option::is_none")]
    pub archived: Option<bool>,
    #[serde(rename = "is_child", skip_serializing_if = "Option::is_none")]
    pub is_child: Option<bool>,
    #[serde(rename = "question_type", skip_serializing_if = "Option::is_none")]
    pub question_type: Option<String>,
    #[serde(rename = "required", skip_serializing_if = "Option::is_none")]
    pub required: Option<bool>,
    #[serde(rename = "force_required")]
    pub force_required: bool,
    #[serde(rename = "allow_guidance_override")]
    pub allow_guidance_override: bool,
    #[serde(rename = "default", skip_serializing_if = "Option::is_none")]
    pub default: Option<bool>,
    #[serde(rename = "guidance")]
    pub guidance: String,
    #[serde(rename = "title")]
    pub title: String,
    #[serde(rename = "field")]
    pub field: Vec<serde_json::Value>,
}

impl UpdateQuestionBankQuestionRequest {
    pub fn new(section_id: i32, force_required: bool, allow_guidance_override: bool, guidance: String, title: String, field: Vec<serde_json::Value>) -> UpdateQuestionBankQuestionRequest {
        UpdateQuestionBankQuestionRequest {
            section_id,
            user_id: None,
            team_ids: None,
            locked: None,
            archived: None,
            is_child: None,
            question_type: None,
            required: None,
            force_required,
            allow_guidance_override,
            default: None,
            guidance,
            title,
            field,
        }
    }
}

