/*
 * HDRUK Gateway API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdatePublicationsRequest {
    #[serde(rename = "paper_title", skip_serializing_if = "Option::is_none")]
    pub paper_title: Option<String>,
    #[serde(rename = "authors", skip_serializing_if = "Option::is_none")]
    pub authors: Option<String>,
    #[serde(rename = "year_of_publication", skip_serializing_if = "Option::is_none")]
    pub year_of_publication: Option<String>,
    #[serde(rename = "paper_doi", skip_serializing_if = "Option::is_none")]
    pub paper_doi: Option<String>,
    #[serde(rename = "publication_type", skip_serializing_if = "Option::is_none")]
    pub publication_type: Option<String>,
    #[serde(rename = "journal_name", skip_serializing_if = "Option::is_none")]
    pub journal_name: Option<String>,
    #[serde(rename = "abstract", skip_serializing_if = "Option::is_none")]
    pub r#abstract: Option<String>,
    #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<Status>,
    #[serde(rename = "datasets", skip_serializing_if = "Option::is_none")]
    pub datasets: Option<Vec<models::CreatePublicationsRequestDatasetsInner>>,
    #[serde(rename = "tools", skip_serializing_if = "Option::is_none")]
    pub tools: Option<Vec<models::CreatePublicationsRequestToolsInner>>,
}

impl UpdatePublicationsRequest {
    pub fn new() -> UpdatePublicationsRequest {
        UpdatePublicationsRequest {
            paper_title: None,
            authors: None,
            year_of_publication: None,
            paper_doi: None,
            publication_type: None,
            journal_name: None,
            r#abstract: None,
            url: None,
            status: None,
            datasets: None,
            tools: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "ACTIVE")]
    Active,
    #[serde(rename = "DRAFT")]
    Draft,
    #[serde(rename = "ARCHIVED")]
    Archived,
}

impl Default for Status {
    fn default() -> Status {
        Self::Active
    }
}

