/*
 * HDRUK Gateway API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateUserDarApplicationRequestAnswersInnerAnswer {
    #[serde(rename = "value", skip_serializing_if = "Option::is_none")]
    pub value: Option<String>,
}

impl UpdateUserDarApplicationRequestAnswersInnerAnswer {
    pub fn new() -> UpdateUserDarApplicationRequestAnswersInnerAnswer {
        UpdateUserDarApplicationRequestAnswersInnerAnswer {
            value: None,
        }
    }
}

