/*
 * HDRUK Gateway API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateApplicationsRequest {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "image_link")]
    pub image_link: String,
    #[serde(rename = "description")]
    pub description: String,
    #[serde(rename = "team_id")]
    pub team_id: i32,
    #[serde(rename = "user_id")]
    pub user_id: i32,
    #[serde(rename = "enabled")]
    pub enabled: bool,
    #[serde(rename = "permissions")]
    pub permissions: Vec<serde_json::Value>,
    #[serde(rename = "notifications", skip_serializing_if = "Option::is_none")]
    pub notifications: Option<Vec<serde_json::Value>>,
}

impl UpdateApplicationsRequest {
    pub fn new(name: String, image_link: String, description: String, team_id: i32, user_id: i32, enabled: bool, permissions: Vec<serde_json::Value>) -> UpdateApplicationsRequest {
        UpdateApplicationsRequest {
            name,
            image_link,
            description,
            team_id,
            user_id,
            enabled,
            permissions,
            notifications: None,
        }
    }
}

