/*
 * HDRUK Gateway API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateToolsRequest {
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "license", skip_serializing_if = "Option::is_none")]
    pub license: Option<i32>,
    #[serde(rename = "tech_stack", skip_serializing_if = "Option::is_none")]
    pub tech_stack: Option<String>,
    #[serde(rename = "category_id", skip_serializing_if = "Option::is_none")]
    pub category_id: Option<i32>,
    #[serde(rename = "user_id", skip_serializing_if = "Option::is_none")]
    pub user_id: Option<i32>,
    #[serde(rename = "team_id", skip_serializing_if = "Option::is_none")]
    pub team_id: Option<i32>,
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Vec<i64>>,
    #[serde(rename = "dataset", skip_serializing_if = "Option::is_none")]
    pub dataset: Option<Vec<models::CreateToolsIntegrationsRequestDatasetInner>>,
    #[serde(rename = "enabled", skip_serializing_if = "Option::is_none")]
    pub enabled: Option<i32>,
    #[serde(rename = "programming_language", skip_serializing_if = "Option::is_none")]
    pub programming_language: Option<Vec<i64>>,
    #[serde(rename = "programming_package", skip_serializing_if = "Option::is_none")]
    pub programming_package: Option<Vec<i64>>,
    #[serde(rename = "type_category", skip_serializing_if = "Option::is_none")]
    pub type_category: Option<Vec<i64>>,
    #[serde(rename = "associated_authors", skip_serializing_if = "Option::is_none")]
    pub associated_authors: Option<String>,
    #[serde(rename = "contact_address", skip_serializing_if = "Option::is_none")]
    pub contact_address: Option<String>,
    #[serde(rename = "publications", skip_serializing_if = "Option::is_none")]
    pub publications: Option<Vec<models::CreateToolsIntegrationsRequestPublicationsInner>>,
    #[serde(rename = "durs", skip_serializing_if = "Option::is_none")]
    pub durs: Option<Vec<i64>>,
    #[serde(rename = "collections", skip_serializing_if = "Option::is_none")]
    pub collections: Option<Vec<models::CreateToolsRequestCollectionsInner>>,
    #[serde(rename = "any_dataset", skip_serializing_if = "Option::is_none")]
    pub any_dataset: Option<bool>,
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<Status>,
}

impl UpdateToolsRequest {
    pub fn new() -> UpdateToolsRequest {
        UpdateToolsRequest {
            name: None,
            url: None,
            description: None,
            license: None,
            tech_stack: None,
            category_id: None,
            user_id: None,
            team_id: None,
            tags: None,
            dataset: None,
            enabled: None,
            programming_language: None,
            programming_package: None,
            type_category: None,
            associated_authors: None,
            contact_address: None,
            publications: None,
            durs: None,
            collections: None,
            any_dataset: None,
            status: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "ACTIVE")]
    Active,
    #[serde(rename = "DRAFT")]
    Draft,
    #[serde(rename = "ARCHIVED")]
    Archived,
}

impl Default for Status {
    fn default() -> Status {
        Self::Active
    }
}

