/*
 * HDRUK Gateway API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UploadDurRequest {
    #[serde(rename = "user_id", skip_serializing_if = "Option::is_none")]
    pub user_id: Option<i32>,
    #[serde(rename = "team_id", skip_serializing_if = "Option::is_none")]
    pub team_id: Option<i32>,
    #[serde(rename = "project_title", skip_serializing_if = "Option::is_none")]
    pub project_title: Option<String>,
    #[serde(rename = "project_id_text", skip_serializing_if = "Option::is_none")]
    pub project_id_text: Option<String>,
    #[serde(rename = "organisation_name", skip_serializing_if = "Option::is_none")]
    pub organisation_name: Option<String>,
    #[serde(rename = "organisation_id", skip_serializing_if = "Option::is_none")]
    pub organisation_id: Option<String>,
    #[serde(rename = "organisation_sector", skip_serializing_if = "Option::is_none")]
    pub organisation_sector: Option<String>,
    #[serde(rename = "non_gateway_applicants", skip_serializing_if = "Option::is_none")]
    pub non_gateway_applicants: Option<String>,
    #[serde(rename = "applicant_id", skip_serializing_if = "Option::is_none")]
    pub applicant_id: Option<i32>,
    #[serde(rename = "funders_and_sponsors", skip_serializing_if = "Option::is_none")]
    pub funders_and_sponsors: Option<String>,
    #[serde(rename = "accredited_researcher_status", skip_serializing_if = "Option::is_none")]
    pub accredited_researcher_status: Option<String>,
    #[serde(rename = "sublicence_arrangements", skip_serializing_if = "Option::is_none")]
    pub sublicence_arrangements: Option<String>,
    #[serde(rename = "lay_summary", skip_serializing_if = "Option::is_none")]
    pub lay_summary: Option<String>,
    #[serde(rename = "public_benefit_statement", skip_serializing_if = "Option::is_none")]
    pub public_benefit_statement: Option<String>,
    #[serde(rename = "request_category_type", skip_serializing_if = "Option::is_none")]
    pub request_category_type: Option<String>,
    #[serde(rename = "technical_summary", skip_serializing_if = "Option::is_none")]
    pub technical_summary: Option<String>,
    #[serde(rename = "other_approval_committees", skip_serializing_if = "Option::is_none")]
    pub other_approval_committees: Option<String>,
    #[serde(rename = "project_start_date", skip_serializing_if = "Option::is_none")]
    pub project_start_date: Option<String>,
    #[serde(rename = "project_end_date", skip_serializing_if = "Option::is_none")]
    pub project_end_date: Option<String>,
    #[serde(rename = "latest_approval_date", skip_serializing_if = "Option::is_none")]
    pub latest_approval_date: Option<String>,
    #[serde(rename = "data_sensitivity_level", skip_serializing_if = "Option::is_none")]
    pub data_sensitivity_level: Option<String>,
    #[serde(rename = "legal_basis_for_data_article6", skip_serializing_if = "Option::is_none")]
    pub legal_basis_for_data_article6: Option<String>,
    #[serde(rename = "legal_basis_for_data_article9", skip_serializing_if = "Option::is_none")]
    pub legal_basis_for_data_article9: Option<String>,
    #[serde(rename = "duty_of_confidentiality", skip_serializing_if = "Option::is_none")]
    pub duty_of_confidentiality: Option<String>,
    #[serde(rename = "national_data_optout", skip_serializing_if = "Option::is_none")]
    pub national_data_optout: Option<String>,
    #[serde(rename = "request_frequency", skip_serializing_if = "Option::is_none")]
    pub request_frequency: Option<String>,
    #[serde(rename = "dataset_linkage_description", skip_serializing_if = "Option::is_none")]
    pub dataset_linkage_description: Option<String>,
    #[serde(rename = "confidential_data_description", skip_serializing_if = "Option::is_none")]
    pub confidential_data_description: Option<String>,
    #[serde(rename = "access_date", skip_serializing_if = "Option::is_none")]
    pub access_date: Option<String>,
    #[serde(rename = "access_type", skip_serializing_if = "Option::is_none")]
    pub access_type: Option<String>,
    #[serde(rename = "privacy_enhancements", skip_serializing_if = "Option::is_none")]
    pub privacy_enhancements: Option<String>,
    #[serde(rename = "datasets", skip_serializing_if = "Option::is_none")]
    pub datasets: Option<Vec<models::CreateDurRequestDatasetsInner>>,
}

impl UploadDurRequest {
    pub fn new() -> UploadDurRequest {
        UploadDurRequest {
            user_id: None,
            team_id: None,
            project_title: None,
            project_id_text: None,
            organisation_name: None,
            organisation_id: None,
            organisation_sector: None,
            non_gateway_applicants: None,
            applicant_id: None,
            funders_and_sponsors: None,
            accredited_researcher_status: None,
            sublicence_arrangements: None,
            lay_summary: None,
            public_benefit_statement: None,
            request_category_type: None,
            technical_summary: None,
            other_approval_committees: None,
            project_start_date: None,
            project_end_date: None,
            latest_approval_date: None,
            data_sensitivity_level: None,
            legal_basis_for_data_article6: None,
            legal_basis_for_data_article9: None,
            duty_of_confidentiality: None,
            national_data_optout: None,
            request_frequency: None,
            dataset_linkage_description: None,
            confidential_data_description: None,
            access_date: None,
            access_type: None,
            privacy_enhancements: None,
            datasets: None,
        }
    }
}

